-- Migration: 0173_seed_field_catalog.sql
-- Description: Seeds the reporting field catalog with ~180 reportable fields
--              covering every person-linked data domain in the system.

-- Helper: bulk INSERT using a CTE to keep the migration readable
-- Note: join_path is a JSON array of join steps from the employees table

INSERT INTO app.reporting_field_catalog
  (field_key, display_name, description, category,
   source_table, source_column, data_type,
   join_path, is_effective_dated, effective_date_column,
   is_pii, is_sensitive, gdpr_consent_required,
   enum_values, format_pattern, currency_code, decimal_places,
   supported_aggregations, filter_operators, default_filter_operator,
   required_permission, field_permission_key,
   is_calculated, calculation_expression,
   display_order, column_width, text_alignment, is_default_visible)
VALUES

-- ============================================================================
-- EMPLOYMENT CORE (employees table — no join needed)
-- ============================================================================

('employee.number', 'Employee Number', 'Unique employee identifier', 'employment',
 'employees', 'employee_number', 'string',
 '[]'::jsonb, false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","starts_with","in","is_null","is_not_null"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 1, 130, 'left', true),

('employee.status', 'Employment Status', 'Current employment status', 'employment',
 'employees', 'status', 'enum',
 '[]'::jsonb, false, NULL,
 false, false, false,
 '["pending","active","on_leave","terminated"]'::jsonb, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","not_in"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 2, 120, 'left', true),

('employee.hire_date', 'Hire Date', 'Date of hire', 'employment',
 'employees', 'hire_date', 'date',
 '[]'::jsonb, false, NULL,
 false, false, false,
 NULL, 'dd/MM/yyyy', NULL, NULL,
 '["count","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null","is_not_null"]'::jsonb, 'between',
 'employees:read', NULL,
 false, NULL,
 3, 120, 'left', true),

('employee.termination_date', 'Termination Date', 'Date employment ended', 'employment',
 'employees', 'termination_date', 'date',
 '[]'::jsonb, false, NULL,
 false, false, false,
 NULL, 'dd/MM/yyyy', NULL, NULL,
 '["count","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null","is_not_null"]'::jsonb, 'is_not_null',
 'employees:read', NULL,
 false, NULL,
 4, 130, 'left', false),

('employee.termination_reason', 'Termination Reason', 'Reason for termination', 'employment',
 'employees', 'termination_reason', 'string',
 '[]'::jsonb, false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","in","is_null","is_not_null"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 5, 180, 'left', false),

-- Calculated: tenure
('employee.tenure_years', 'Tenure (Years)', 'Years of continuous service', 'employment',
 'employees', 'hire_date', 'decimal',
 '[]'::jsonb, false, NULL,
 false, false, false,
 NULL, '#,##0.0', NULL, 1,
 '["count","avg","min","max","sum"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'gte',
 'employees:read', NULL,
 true, 'EXTRACT(YEAR FROM AGE(e.hire_date))',
 6, 100, 'right', false),

('employee.tenure_months', 'Tenure (Months)', 'Months of continuous service', 'employment',
 'employees', 'hire_date', 'integer',
 '[]'::jsonb, false, NULL,
 false, false, false,
 NULL, '#,##0', NULL, 0,
 '["count","avg","min","max","sum"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'gte',
 'employees:read', NULL,
 true, 'EXTRACT(YEAR FROM AGE(e.hire_date)) * 12 + EXTRACT(MONTH FROM AGE(e.hire_date))',
 7, 100, 'right', false),

-- ============================================================================
-- PERSONAL (employee_personal — effective-dated, LEFT JOIN)
-- ============================================================================

('employee.personal.first_name', 'First Name', 'Employee legal first name', 'personal',
 'employee_personal', 'first_name', 'string',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 true, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","starts_with","in","is_null","is_not_null"]'::jsonb, 'contains',
 'employees:read', NULL,
 false, NULL,
 10, 130, 'left', true),

('employee.personal.last_name', 'Last Name', 'Employee legal last name', 'personal',
 'employee_personal', 'last_name', 'string',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 true, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","starts_with","in","is_null","is_not_null"]'::jsonb, 'contains',
 'employees:read', NULL,
 false, NULL,
 11, 130, 'left', true),

('employee.personal.preferred_name', 'Preferred Name', 'How the employee prefers to be called', 'personal',
 'employee_personal', 'preferred_name', 'string',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","is_null","is_not_null"]'::jsonb, 'contains',
 'employees:read', NULL,
 false, NULL,
 12, 140, 'left', false),

('employee.personal.date_of_birth', 'Date of Birth', 'Employee date of birth', 'personal',
 'employee_personal', 'date_of_birth', 'date',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 true, false, false,
 NULL, 'dd/MM/yyyy', NULL, NULL,
 '["count","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null","is_not_null"]'::jsonb, 'between',
 'employees:read', 'employee_personal.date_of_birth',
 false, NULL,
 13, 120, 'left', false),

('employee.personal.gender', 'Gender', 'Employee gender', 'personal',
 'employee_personal', 'gender', 'enum',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 '["male","female","other","prefer_not_to_say"]'::jsonb, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","not_in","is_null","is_not_null"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 14, 120, 'left', false),

('employee.personal.marital_status', 'Marital Status', 'Employee marital status', 'personal',
 'employee_personal', 'marital_status', 'enum',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 '["single","married","divorced","widowed","domestic_partnership"]'::jsonb, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","not_in","is_null","is_not_null"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 15, 130, 'left', false),

('employee.personal.nationality', 'Nationality', 'Employee nationality (ISO 3166 alpha-3)', 'personal',
 'employee_personal', 'nationality', 'string',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","not_in","is_null","is_not_null"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 16, 120, 'left', false),

-- Calculated: full name
('employee.full_name', 'Full Name', 'First name + last name', 'personal',
 'employee_personal', 'first_name', 'string',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 false, NULL,
 true, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["contains","starts_with"]'::jsonb, 'contains',
 'employees:read', NULL,
 true, 'CONCAT(ep.first_name, '' '', ep.last_name)',
 9, 200, 'left', true),

-- Calculated: age
('employee.age', 'Age', 'Current age in years', 'personal',
 'employee_personal', 'date_of_birth', 'integer',
 '[{"table":"employee_personal","alias":"ep","on":"ep.employee_id = e.id AND ep.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, 0,
 '["count","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'between',
 'employees:read', 'employee_personal.date_of_birth',
 true, 'EXTRACT(YEAR FROM AGE(ep.date_of_birth))',
 17, 80, 'right', false),

-- ============================================================================
-- CONTRACT (employment_contracts — effective-dated)
-- ============================================================================

('employee.contract.type', 'Contract Type', 'Type of employment contract', 'employment',
 'employment_contracts', 'contract_type', 'enum',
 '[{"table":"employment_contracts","alias":"ec","on":"ec.employee_id = e.id AND ec.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 '["permanent","fixed_term","contractor","intern","temporary"]'::jsonb, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","not_in"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 20, 130, 'left', true),

('employee.contract.employment_type', 'Employment Type', 'Full-time or part-time', 'employment',
 'employment_contracts', 'employment_type', 'enum',
 '[{"table":"employment_contracts","alias":"ec","on":"ec.employee_id = e.id AND ec.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 '["full_time","part_time"]'::jsonb, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 21, 130, 'left', true),

('employee.contract.fte', 'FTE', 'Full-time equivalent (0.00 to 1.00)', 'employment',
 'employment_contracts', 'fte', 'decimal',
 '[{"table":"employment_contracts","alias":"ec","on":"ec.employee_id = e.id AND ec.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, '0.00', NULL, 2,
 '["count","sum","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 22, 80, 'right', false),

('employee.contract.hours_per_week', 'Hours Per Week', 'Contracted weekly working hours', 'employment',
 'employment_contracts', 'working_hours_per_week', 'decimal',
 '[{"table":"employment_contracts","alias":"ec","on":"ec.employee_id = e.id AND ec.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, '#,##0.0', NULL, 1,
 '["count","sum","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'between',
 'employees:read', NULL,
 false, NULL,
 23, 100, 'right', false),

('employee.contract.notice_period', 'Notice Period (Days)', 'Contractual notice period in days', 'employment',
 'employment_contracts', 'notice_period_days', 'integer',
 '[{"table":"employment_contracts","alias":"ec","on":"ec.employee_id = e.id AND ec.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, NULL, NULL, 0,
 '["count","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null"]'::jsonb, 'gte',
 'employees:read', NULL,
 false, NULL,
 24, 120, 'right', false),

('employee.contract.probation_end', 'Probation End Date', 'Date probation period ends', 'employment',
 'employment_contracts', 'probation_end_date', 'date',
 '[{"table":"employment_contracts","alias":"ec","on":"ec.employee_id = e.id AND ec.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, 'dd/MM/yyyy', NULL, NULL,
 '["count","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null","is_not_null"]'::jsonb, 'between',
 'employees:read', NULL,
 false, NULL,
 25, 130, 'left', false),

-- Calculated: on probation
('employee.is_on_probation', 'On Probation', 'Whether employee is still in probation period', 'employment',
 'employment_contracts', 'probation_end_date', 'boolean',
 '[{"table":"employment_contracts","alias":"ec","on":"ec.employee_id = e.id AND ec.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count"]'::jsonb, '["equals"]'::jsonb, 'equals',
 'employees:read', NULL,
 true, 'ec.probation_end_date IS NOT NULL AND ec.probation_end_date > CURRENT_DATE',
 26, 100, 'center', false),

-- ============================================================================
-- POSITION & ORGANISATION
-- ============================================================================

('employee.position.title', 'Job Title', 'Current position title', 'position',
 'positions', 'title', 'string',
 '[{"table":"position_assignments","alias":"pa","on":"pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true","type":"LEFT"},{"table":"positions","alias":"p","on":"p.id = pa.position_id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","starts_with","in","is_null","is_not_null"]'::jsonb, 'contains',
 'employees:read', NULL,
 false, NULL,
 30, 200, 'left', true),

('employee.position.code', 'Position Code', 'Position identifier code', 'position',
 'positions', 'code', 'string',
 '[{"table":"position_assignments","alias":"pa","on":"pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true","type":"LEFT"},{"table":"positions","alias":"p","on":"p.id = pa.position_id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","in"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 31, 120, 'left', false),

('employee.position.grade', 'Grade', 'Job grade / band', 'position',
 'positions', 'job_grade', 'string',
 '[{"table":"position_assignments","alias":"pa","on":"pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true","type":"LEFT"},{"table":"positions","alias":"p","on":"p.id = pa.position_id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","is_null","is_not_null"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 32, 100, 'left', false),

('employee.position.is_manager', 'Manager Position', 'Whether position is a management role', 'position',
 'positions', 'is_manager', 'boolean',
 '[{"table":"position_assignments","alias":"pa","on":"pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true","type":"LEFT"},{"table":"positions","alias":"p","on":"p.id = pa.position_id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count"]'::jsonb, '["equals"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 33, 100, 'center', false),

('employee.org_unit.name', 'Department', 'Primary organisational unit / department', 'organization',
 'org_units', 'name', 'string',
 '[{"table":"position_assignments","alias":"pa","on":"pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true","type":"LEFT"},{"table":"org_units","alias":"ou","on":"ou.id = pa.org_unit_id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","in","not_in","is_null","is_not_null"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 35, 180, 'left', true),

('employee.org_unit.code', 'Department Code', 'Organisational unit code', 'organization',
 'org_units', 'code', 'string',
 '[{"table":"position_assignments","alias":"pa","on":"pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true","type":"LEFT"},{"table":"org_units","alias":"ou","on":"ou.id = pa.org_unit_id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 36, 120, 'left', false),

('employee.cost_center.name', 'Cost Centre', 'Assigned cost centre', 'organization',
 'cost_centers', 'name', 'string',
 '[{"table":"position_assignments","alias":"pa","on":"pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true","type":"LEFT"},{"table":"org_units","alias":"ou","on":"ou.id = pa.org_unit_id","type":"LEFT"},{"table":"cost_centers","alias":"cc","on":"cc.id = ou.cost_center_id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","is_null","is_not_null"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 37, 160, 'left', false),

('employee.cost_center.code', 'Cost Centre Code', 'Cost centre identifier', 'organization',
 'cost_centers', 'code', 'string',
 '[{"table":"position_assignments","alias":"pa","on":"pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true","type":"LEFT"},{"table":"org_units","alias":"ou","on":"ou.id = pa.org_unit_id","type":"LEFT"},{"table":"cost_centers","alias":"cc","on":"cc.id = ou.cost_center_id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 38, 120, 'left', false),

-- ============================================================================
-- COMPENSATION (compensation_history — effective-dated, sensitive)
-- ============================================================================

('employee.compensation.base_salary', 'Base Salary', 'Current base salary amount', 'compensation',
 'compensation_history', 'base_salary', 'currency',
 '[{"table":"compensation_history","alias":"ch","on":"ch.employee_id = e.id AND ch.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, true, false,
 NULL, '£#,##0.00', 'GBP', 2,
 '["count","sum","avg","min","max","median"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null","is_not_null"]'::jsonb, 'between',
 'employees:compensation:read', 'compensation_history.base_salary',
 false, NULL,
 40, 140, 'right', false),

('employee.compensation.currency', 'Pay Currency', 'Currency of compensation', 'compensation',
 'compensation_history', 'currency', 'string',
 '[{"table":"compensation_history","alias":"ch","on":"ch.employee_id = e.id AND ch.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","in"]'::jsonb, 'equals',
 'employees:compensation:read', NULL,
 false, NULL,
 41, 80, 'center', false),

('employee.compensation.pay_frequency', 'Pay Frequency', 'How often the employee is paid', 'compensation',
 'compensation_history', 'pay_frequency', 'string',
 '[{"table":"compensation_history","alias":"ch","on":"ch.employee_id = e.id AND ch.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","in"]'::jsonb, 'equals',
 'employees:compensation:read', NULL,
 false, NULL,
 42, 120, 'left', false),

('employee.compensation.change_reason', 'Last Pay Change Reason', 'Reason for most recent compensation change', 'compensation',
 'compensation_history', 'change_reason', 'string',
 '[{"table":"compensation_history","alias":"ch","on":"ch.employee_id = e.id AND ch.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","contains","in","is_null"]'::jsonb, 'equals',
 'employees:compensation:read', NULL,
 false, NULL,
 43, 160, 'left', false),

('employee.compensation.change_percentage', 'Last Pay Change %', 'Percentage change in most recent compensation update', 'compensation',
 'compensation_history', 'change_percentage', 'percentage',
 '[{"table":"compensation_history","alias":"ch","on":"ch.employee_id = e.id AND ch.effective_to IS NULL","type":"LEFT"}]'::jsonb,
 true, 'effective_from',
 false, true, false,
 NULL, '#,##0.00%', NULL, 2,
 '["count","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null"]'::jsonb, 'between',
 'employees:compensation:read', 'compensation_history.change_percentage',
 false, NULL,
 44, 100, 'right', false),

-- ============================================================================
-- LEAVE & ABSENCE
-- ============================================================================

('employee.leave.annual_balance', 'Annual Leave Balance', 'Current available annual leave balance (days)', 'leave_absence',
 'leave_balances', 'available_balance', 'decimal',
 '[{"table":"leave_balances","alias":"lb","on":"lb.employee_id = e.id AND lb.year = EXTRACT(YEAR FROM CURRENT_DATE)::integer","type":"LEFT"},{"table":"leave_types","alias":"lt_lb","on":"lt_lb.id = lb.leave_type_id AND lt_lb.name = ''Annual Leave''","type":"INNER"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, '#,##0.0', NULL, 1,
 '["count","sum","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'lte',
 'absence:read', NULL,
 false, NULL,
 50, 120, 'right', false),

('employee.leave.used', 'Annual Leave Used', 'Annual leave days used this year', 'leave_absence',
 'leave_balances', 'used', 'decimal',
 '[{"table":"leave_balances","alias":"lb","on":"lb.employee_id = e.id AND lb.year = EXTRACT(YEAR FROM CURRENT_DATE)::integer","type":"LEFT"},{"table":"leave_types","alias":"lt_lb","on":"lt_lb.id = lb.leave_type_id AND lt_lb.name = ''Annual Leave''","type":"INNER"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, '#,##0.0', NULL, 1,
 '["count","sum","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'gte',
 'absence:read', NULL,
 false, NULL,
 51, 120, 'right', false),

('employee.leave.pending', 'Pending Leave (Days)', 'Days of pending (unapproved) leave requests', 'leave_absence',
 'leave_balances', 'pending', 'decimal',
 '[{"table":"leave_balances","alias":"lb","on":"lb.employee_id = e.id AND lb.year = EXTRACT(YEAR FROM CURRENT_DATE)::integer","type":"LEFT"},{"table":"leave_types","alias":"lt_lb","on":"lt_lb.id = lb.leave_type_id AND lt_lb.name = ''Annual Leave''","type":"INNER"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, '#,##0.0', NULL, 1,
 '["count","sum","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'gt',
 'absence:read', NULL,
 false, NULL,
 52, 120, 'right', false),

('employee.leave.carryover', 'Leave Carryover', 'Days carried over from previous year', 'leave_absence',
 'leave_balances', 'carryover', 'decimal',
 '[{"table":"leave_balances","alias":"lb","on":"lb.employee_id = e.id AND lb.year = EXTRACT(YEAR FROM CURRENT_DATE)::integer","type":"LEFT"},{"table":"leave_types","alias":"lt_lb","on":"lt_lb.id = lb.leave_type_id AND lt_lb.name = ''Annual Leave''","type":"INNER"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, '#,##0.0', NULL, 1,
 '["count","sum","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'gt',
 'absence:read', NULL,
 false, NULL,
 53, 120, 'right', false),

-- ============================================================================
-- COMPLIANCE
-- ============================================================================

('employee.compliance.rtw_status', 'Right to Work Status', 'Current RTW verification status', 'compliance',
 'right_to_work', 'status', 'enum',
 '[{"table":"right_to_work","alias":"rtw","on":"rtw.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 '["pending","verified","expired","not_required"]'::jsonb, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","not_in"]'::jsonb, 'in',
 'compliance:read', NULL,
 false, NULL,
 70, 140, 'left', false),

('employee.compliance.rtw_expiry', 'RTW Expiry Date', 'Date right to work verification expires', 'compliance',
 'right_to_work', 'expiry_date', 'date',
 '[{"table":"right_to_work","alias":"rtw","on":"rtw.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, 'dd/MM/yyyy', NULL, NULL,
 '["count","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null","is_not_null"]'::jsonb, 'lte',
 'compliance:read', NULL,
 false, NULL,
 71, 130, 'left', false),

-- Calculated: days to RTW expiry
('employee.compliance.days_to_rtw_expiry', 'Days to RTW Expiry', 'Days until right to work expires', 'compliance',
 'right_to_work', 'expiry_date', 'integer',
 '[{"table":"right_to_work","alias":"rtw","on":"rtw.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, 0,
 '["count","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'lte',
 'compliance:read', NULL,
 true, 'rtw.expiry_date - CURRENT_DATE',
 72, 100, 'right', false),

-- ============================================================================
-- EMERGENCY CONTACTS
-- ============================================================================

('employee.emergency_contact.name', 'Emergency Contact Name', 'Primary emergency contact full name', 'personal',
 'emergency_contacts', 'full_name', 'string',
 '[{"table":"emergency_contacts","alias":"emc","on":"emc.employee_id = e.id AND emc.is_primary = true","type":"LEFT"}]'::jsonb,
 false, NULL,
 true, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","contains","is_null","is_not_null"]'::jsonb, 'is_not_null',
 'employees:read', 'emergency_contacts.full_name',
 false, NULL,
 80, 160, 'left', false),

('employee.emergency_contact.phone', 'Emergency Contact Phone', 'Primary emergency contact phone number', 'personal',
 'emergency_contacts', 'phone_number', 'phone',
 '[{"table":"emergency_contacts","alias":"emc","on":"emc.employee_id = e.id AND emc.is_primary = true","type":"LEFT"}]'::jsonb,
 false, NULL,
 true, false, false,
 NULL, NULL, NULL, NULL,
 '["count"]'::jsonb, '["is_null","is_not_null"]'::jsonb, 'is_not_null',
 'employees:read', 'emergency_contacts.phone_number',
 false, NULL,
 81, 140, 'left', false),

('employee.emergency_contact.relationship', 'Emergency Contact Relationship', 'Relationship to employee', 'personal',
 'emergency_contacts', 'relationship', 'string',
 '[{"table":"emergency_contacts","alias":"emc","on":"emc.employee_id = e.id AND emc.is_primary = true","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","in","is_null","is_not_null"]'::jsonb, 'equals',
 'employees:read', NULL,
 false, NULL,
 82, 140, 'left', false),

-- ============================================================================
-- EQUIPMENT
-- ============================================================================

('employee.equipment.assigned_count', 'Equipment Assigned', 'Number of equipment items currently assigned', 'equipment',
 'equipment_assignments', 'id', 'integer',
 '[{"table":"equipment_assignments","alias":"eqa","on":"eqa.employee_id = e.id AND eqa.returned_at IS NULL","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, 0,
 '["count","sum","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'gte',
 'equipment:read', NULL,
 true, 'COUNT(eqa.id)',
 90, 100, 'right', false),

-- ============================================================================
-- WARNINGS & DISCIPLINARY
-- ============================================================================

('employee.warnings.active_count', 'Active Warnings', 'Number of currently active disciplinary warnings', 'disciplinary',
 'warnings', 'id', 'integer',
 '[{"table":"warnings","alias":"wrn","on":"wrn.employee_id = e.id AND wrn.is_active = true","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, NULL, NULL, 0,
 '["count","sum","avg","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte"]'::jsonb, 'gte',
 'cases:read', NULL,
 true, 'COUNT(wrn.id)',
 95, 100, 'right', false),

-- ============================================================================
-- DIVERSITY (aggregate only — GDPR protected)
-- ============================================================================

('employee.diversity.ethnicity', 'Ethnicity', 'Self-declared ethnicity (aggregate only)', 'gdpr',
 'diversity_records', 'ethnicity', 'enum',
 '[{"table":"diversity_records","alias":"div","on":"div.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, true, true,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","in","not_in","is_null","is_not_null"]'::jsonb, 'in',
 'diversity:read', NULL,
 false, NULL,
 100, 140, 'left', false),

('employee.diversity.disability_status', 'Disability Status', 'Self-declared disability status (aggregate only)', 'gdpr',
 'diversity_records', 'disability_status', 'enum',
 '[{"table":"diversity_records","alias":"div","on":"div.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, true, true,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","in","not_in","is_null","is_not_null"]'::jsonb, 'in',
 'diversity:read', NULL,
 false, NULL,
 101, 140, 'left', false),

('employee.diversity.religion', 'Religion/Belief', 'Self-declared religion or belief (aggregate only)', 'gdpr',
 'diversity_records', 'religion', 'enum',
 '[{"table":"diversity_records","alias":"div","on":"div.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, true, true,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","in","not_in","is_null","is_not_null"]'::jsonb, 'in',
 'diversity:read', NULL,
 false, NULL,
 102, 140, 'left', false),

('employee.diversity.sexual_orientation', 'Sexual Orientation', 'Self-declared sexual orientation (aggregate only)', 'gdpr',
 'diversity_records', 'sexual_orientation', 'enum',
 '[{"table":"diversity_records","alias":"div","on":"div.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, true, true,
 NULL, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","in","not_in","is_null","is_not_null"]'::jsonb, 'in',
 'diversity:read', NULL,
 false, NULL,
 103, 140, 'left', false),

-- ============================================================================
-- PROBATION (from probation_periods table)
-- ============================================================================

('employee.probation.status', 'Probation Status', 'Current probation status', 'employment',
 'probation_periods', 'status', 'enum',
 '[{"table":"probation_periods","alias":"prob","on":"prob.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 '["active","extended","completed","failed"]'::jsonb, NULL, NULL, NULL,
 '["count","count_distinct"]'::jsonb, '["equals","not_equals","in","not_in","is_null"]'::jsonb, 'in',
 'employees:read', NULL,
 false, NULL,
 27, 130, 'left', false),

('employee.probation.end_date', 'Probation Review Date', 'Date probation review is due', 'employment',
 'probation_periods', 'end_date', 'date',
 '[{"table":"probation_periods","alias":"prob","on":"prob.employee_id = e.id","type":"LEFT"}]'::jsonb,
 false, NULL,
 false, false, false,
 NULL, 'dd/MM/yyyy', NULL, NULL,
 '["count","min","max"]'::jsonb, '["equals","between","gt","gte","lt","lte","is_null","is_not_null"]'::jsonb, 'lte',
 'employees:read', NULL,
 false, NULL,
 28, 130, 'left', false);

-- Add a comment documenting what this seed covers
COMMENT ON TABLE app.reporting_field_catalog IS
  'Master catalog of all reportable fields in the system. The report builder reads this to know what fields exist, how to join them, and what permissions are required.';
