#!/bin/bash
# =============================================================================
# Staffora Backup Sidecar Entrypoint
# =============================================================================
#
# Replaces the previous sleep-loop approach with proper cron scheduling.
# The BACKUP_SCHEDULE env var (cron expression, default "0 2 * * *") controls
# when backups run. Cron runs in the foreground so Docker can manage the process.
#
# Manual backup is still supported:
#   docker exec staffora-backup /scripts/backup-db.sh /backups
# =============================================================================

set -euo pipefail

BACKUP_SCHEDULE="${BACKUP_SCHEDULE:-0 2 * * *}"

echo "[$(date -Iseconds)] Backup sidecar starting..."
echo "  Schedule: ${BACKUP_SCHEDULE}"
echo "  S3 bucket: ${S3_BACKUP_BUCKET:-(not configured, local only)}"

# ---------------------------------------------------------------------------
# Install system dependencies
# ---------------------------------------------------------------------------
echo "[$(date -Iseconds)] Installing cron..."
apt-get update -qq && apt-get install -y -qq cron > /dev/null 2>&1
echo "[$(date -Iseconds)] Cron installed."

if [ -n "${S3_BACKUP_BUCKET:-}" ]; then
  echo "[$(date -Iseconds)] S3 backup enabled. Installing AWS CLI..."
  apt-get install -y -qq awscli > /dev/null 2>&1
  echo "[$(date -Iseconds)] AWS CLI installed."
fi

# ---------------------------------------------------------------------------
# Build the cron job command
# ---------------------------------------------------------------------------
# The backup script and optional S3 cleanup, with all output logged.
CRON_CMD="/scripts/backup-db.sh /backups"

if [ -n "${S3_BACKUP_BUCKET:-}" ]; then
  CRON_CMD="${CRON_CMD} && /scripts/backup-s3-cleanup.sh"
fi

# ---------------------------------------------------------------------------
# Export environment variables so cron jobs inherit them
# ---------------------------------------------------------------------------
# Cron runs in a minimal environment without inheriting Docker env vars.
# Write all relevant env vars to a file that the cron job will source.
ENV_FILE="/etc/backup-env.sh"
{
  echo "# Auto-generated by backup-entrypoint.sh — do not edit"
  echo "export POSTGRES_DB=\"${POSTGRES_DB:-hris}\""
  echo "export POSTGRES_USER=\"${POSTGRES_USER:-hris}\""
  echo "export PGPASSWORD=\"${PGPASSWORD:-}\""
  echo "export PG_HOST=\"${PG_HOST:-postgres}\""
  echo "export BACKUP_RETENTION_DAYS=\"${BACKUP_RETENTION_DAYS:-7}\""
  echo "export S3_BACKUP_BUCKET=\"${S3_BACKUP_BUCKET:-}\""
  echo "export S3_BACKUP_PREFIX=\"${S3_BACKUP_PREFIX:-backups/staffora/}\""
  echo "export S3_BACKUP_STORAGE_CLASS=\"${S3_BACKUP_STORAGE_CLASS:-STANDARD_IA}\""
  echo "export AWS_DEFAULT_REGION=\"${AWS_DEFAULT_REGION:-eu-west-2}\""
  echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID:-}\""
  echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY:-}\""
  echo "export S3_DAILY_RETENTION=\"${S3_DAILY_RETENTION:-30}\""
  echo "export S3_WEEKLY_RETENTION=\"${S3_WEEKLY_RETENTION:-90}\""
  echo "export S3_MONTHLY_RETENTION=\"${S3_MONTHLY_RETENTION:-365}\""
  echo "export VERIFY_BACKUP=\"${VERIFY_BACKUP:-weekly}\""
  echo "export VERIFY_BACKUP_DAY=\"${VERIFY_BACKUP_DAY:-7}\""
  echo "export PATH=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\""
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

# ---------------------------------------------------------------------------
# Write the crontab
# ---------------------------------------------------------------------------
CRONTAB_FILE="/etc/cron.d/staffora-backup"
{
  echo "# Staffora database backup schedule"
  echo "# Generated by backup-entrypoint.sh at $(date -Iseconds)"
  echo "SHELL=/bin/bash"
  echo "${BACKUP_SCHEDULE} root . ${ENV_FILE} && ${CRON_CMD} >> /proc/1/fd/1 2>> /proc/1/fd/2"
  # Crontab files must end with a newline
  echo ""
} > "$CRONTAB_FILE"
chmod 644 "$CRONTAB_FILE"

echo "[$(date -Iseconds)] Crontab installed:"
cat "$CRONTAB_FILE" | sed 's/^/  /'

# ---------------------------------------------------------------------------
# Ensure backup directory exists
# ---------------------------------------------------------------------------
mkdir -p /backups

# ---------------------------------------------------------------------------
# Run an initial backup on first start (optional, controlled by env var)
# ---------------------------------------------------------------------------
if [ "${BACKUP_ON_START:-false}" = "true" ]; then
  echo "[$(date -Iseconds)] Running initial backup on start..."
  # Source the env file so the backup script has the right variables
  . "$ENV_FILE"
  /scripts/backup-db.sh /backups || echo "[$(date -Iseconds)] Initial backup failed, cron will retry on schedule."
fi

# ---------------------------------------------------------------------------
# Start cron in the foreground
# ---------------------------------------------------------------------------
echo "[$(date -Iseconds)] Starting cron daemon in foreground..."
exec cron -f
