// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/legal/terms": {
    params: {};
  };
  "/legal/privacy": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/features" | "/pricing" | "/about" | "/contact" | "/legal/terms" | "/legal/privacy";
  };
  "routes/marketing-layout.tsx": {
    id: "routes/marketing-layout";
    page: "/" | "/features" | "/pricing" | "/about" | "/contact" | "/legal/terms" | "/legal/privacy";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/features.tsx": {
    id: "routes/features";
    page: "/features";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/legal/terms";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/legal/privacy";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/marketing-layout": typeof import("./app/routes/marketing-layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/features": typeof import("./app/routes/features.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
};