/**
 * PDF Generation Worker
 *
 * Generates PDF documents for various Staffora use cases:
 * - LMS Course Completion Certificates
 * - Employment Letters
 * - Case Documentation Bundles
 * - Custom Reports
 *
 * Features:
 * - Template-based PDF generation
 * - Dynamic content rendering
 * - Document storage and retrieval
 * - Notification on completion
 */

import {
  type JobPayload,
  type JobContext,
  type ProcessorRegistration,
  JobTypes,
  StreamKeys,
} from "./base";

// =============================================================================
// Types
// =============================================================================

/**
 * PDF document types
 */
export type PdfDocumentType =
  | "certificate"
  | "employment_letter"
  | "case_bundle"
  | "offer_letter"
  | "termination_letter"
  | "salary_slip"
  | "tax_form"
  | "custom";

/**
 * Base PDF payload
 */
export interface BasePdfPayload {
  /** Document type */
  documentType: PdfDocumentType;
  /** Template to use */
  template: string;
  /** User ID to notify on completion */
  notifyUserId?: string;
}

/**
 * Certificate payload (LMS course completion)
 */
export interface CertificatePayload extends BasePdfPayload {
  documentType: "certificate";
  data: {
    /** Employee information */
    employeeId: string;
    employeeName: string;
    employeeTitle?: string;
    /** Course information */
    courseId: string;
    courseName: string;
    courseDescription?: string;
    /** Completion details */
    completionDate: string;
    score?: number;
    grade?: string;
    /** Certificate metadata */
    certificateNumber?: string;
    issuerName: string;
    issuerTitle: string;
    /** Company branding */
    companyName: string;
    companyLogo?: string;
  };
}

/**
 * Employment letter payload
 */
export interface EmploymentLetterPayload extends BasePdfPayload {
  documentType: "employment_letter";
  data: {
    /** Employee information */
    employeeId: string;
    employeeName: string;
    employeeTitle: string;
    department: string;
    /** Employment details */
    startDate: string;
    endDate?: string;
    employmentType: string;
    salary?: string;
    /** Letter specifics */
    letterType: "verification" | "reference" | "promotion" | "transfer";
    purpose?: string;
    recipientName?: string;
    recipientAddress?: string;
    /** Issuer details */
    issuerName: string;
    issuerTitle: string;
    issuerSignature?: string;
    /** Company details */
    companyName: string;
    companyAddress: string;
    companyPhone?: string;
    companyLogo?: string;
    /** Issue date */
    issueDate: string;
    referenceNumber?: string;
  };
}

/**
 * Case bundle payload (multiple documents)
 */
export interface CaseBundlePayload extends BasePdfPayload {
  documentType: "case_bundle";
  data: {
    /** Case information */
    caseId: string;
    caseNumber: string;
    caseTitle: string;
    caseType: string;
    /** Employee involved */
    employeeId: string;
    employeeName: string;
    /** Documents to include */
    documents: Array<{
      type: string;
      title: string;
      content?: string;
      attachmentId?: string;
    }>;
    /** Timeline of events */
    timeline?: Array<{
      date: string;
      event: string;
      description?: string;
      actor?: string;
    }>;
    /** Notes and summary */
    summary?: string;
    notes?: string[];
    /** Generated by */
    generatedBy: string;
    generatedAt: string;
    /** Company details */
    companyName: string;
    companyLogo?: string;
  };
}

/**
 * Union type for all PDF payloads
 */
export type PdfPayload = CertificatePayload | EmploymentLetterPayload | CaseBundlePayload;

/**
 * PDF generation result
 */
export interface PdfResult {
  /** Document ID */
  documentId: string;
  /** Download URL */
  downloadUrl: string;
  /** File size in bytes */
  fileSize: number;
  /** Number of pages */
  pageCount: number;
  /** Expiration time */
  expiresAt: Date;
}

// =============================================================================
// PDF Generator Abstraction
// =============================================================================

/**
 * PDF generator interface
 * Implement this with your preferred PDF library
 */
export interface PdfGenerator {
  /** Generate a PDF from template and data */
  generate(template: string, data: Record<string, unknown>): Promise<Buffer>;
  /** Merge multiple PDFs into one */
  merge?(pdfs: Buffer[]): Promise<Buffer>;
}

/**
 * PDF generator using pdf-lib for programmatic PDF generation
 */
export class HtmlPdfGenerator implements PdfGenerator {
  async generate(template: string, data: Record<string, unknown>): Promise<Buffer> {
    const { PDFDocument, rgb, StandardFonts } = await import("pdf-lib");

    const pdfDoc = await PDFDocument.create();
    const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const timesRoman = await pdfDoc.embedFont(StandardFonts.TimesRoman);
    const timesRomanBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);

    const page = pdfDoc.addPage([612, 792]); // Letter size
    const { width, height } = page.getSize();
    const margin = 50;

    // Colors
    const primaryColor = rgb(0.1, 0.21, 0.36); // #1a365d
    const secondaryColor = rgb(0.18, 0.22, 0.28); // #2d3748
    const goldColor = rgb(0.79, 0.64, 0.15); // #c9a227
    const grayColor = rgb(0.44, 0.52, 0.59); // #718096

    let y = height - margin;

    switch (template) {
      case "certificate": {
        // Certificate template
        // Border
        page.drawRectangle({
          x: margin - 10,
          y: margin - 10,
          width: width - 2 * margin + 20,
          height: height - 2 * margin + 20,
          borderColor: goldColor,
          borderWidth: 3,
        });

        // Company name
        const companyName = String(data.companyName || "Company");
        const companyWidth = timesRomanBold.widthOfTextAtSize(companyName, 20);
        page.drawText(companyName, {
          x: (width - companyWidth) / 2,
          y: y - 40,
          size: 20,
          font: timesRomanBold,
          color: secondaryColor,
        });
        y -= 80;

        // Certificate title
        const title = "Certificate of Completion";
        const titleWidth = timesRomanBold.widthOfTextAtSize(title, 32);
        page.drawText(title, {
          x: (width - titleWidth) / 2,
          y,
          size: 32,
          font: timesRomanBold,
          color: primaryColor,
        });
        y -= 60;

        // "This certifies that"
        const certifiesText = "This certifies that";
        const certifiesWidth = timesRoman.widthOfTextAtSize(certifiesText, 14);
        page.drawText(certifiesText, {
          x: (width - certifiesWidth) / 2,
          y,
          size: 14,
          font: timesRoman,
          color: grayColor,
        });
        y -= 50;

        // Employee name
        const employeeName = String(data.employeeName || "Employee");
        const nameWidth = timesRomanBold.widthOfTextAtSize(employeeName, 28);
        page.drawText(employeeName, {
          x: (width - nameWidth) / 2,
          y,
          size: 28,
          font: timesRomanBold,
          color: primaryColor,
        });
        y -= 10;
        // Underline
        page.drawLine({
          start: { x: (width - nameWidth) / 2 - 20, y },
          end: { x: (width + nameWidth) / 2 + 20, y },
          thickness: 2,
          color: goldColor,
        });
        y -= 50;

        // "has successfully completed"
        const completedText = "has successfully completed";
        const completedWidth = timesRoman.widthOfTextAtSize(completedText, 14);
        page.drawText(completedText, {
          x: (width - completedWidth) / 2,
          y,
          size: 14,
          font: timesRoman,
          color: grayColor,
        });
        y -= 50;

        // Course name
        const courseName = String(data.courseName || "Course");
        const courseWidth = timesRomanBold.widthOfTextAtSize(courseName, 22);
        page.drawText(courseName, {
          x: (width - courseWidth) / 2,
          y,
          size: 22,
          font: timesRomanBold,
          color: secondaryColor,
        });
        y -= 60;

        // Completion date
        const dateText = `Completed on ${data.completionDate || "Date"}`;
        const dateWidth = timesRoman.widthOfTextAtSize(dateText, 12);
        page.drawText(dateText, {
          x: (width - dateWidth) / 2,
          y,
          size: 12,
          font: timesRoman,
          color: grayColor,
        });
        y -= 80;

        // Signature line
        const sigLineWidth = 200;
        page.drawLine({
          start: { x: (width - sigLineWidth) / 2, y },
          end: { x: (width + sigLineWidth) / 2, y },
          thickness: 1,
          color: secondaryColor,
        });
        y -= 20;

        // Issuer name and title
        const issuerInfo = `${data.issuerName || "Issuer"}, ${data.issuerTitle || "Title"}`;
        const issuerWidth = timesRoman.widthOfTextAtSize(issuerInfo, 12);
        page.drawText(issuerInfo, {
          x: (width - issuerWidth) / 2,
          y,
          size: 12,
          font: timesRoman,
          color: secondaryColor,
        });
        break;
      }

      case "employment_letter": {
        // Letterhead
        const companyName = String(data.companyName || "Company");
        page.drawText(companyName, {
          x: margin,
          y,
          size: 20,
          font: helveticaBold,
          color: primaryColor,
        });
        y -= 20;

        if (data.companyAddress) {
          page.drawText(String(data.companyAddress), {
            x: margin,
            y,
            size: 10,
            font: helveticaFont,
            color: grayColor,
          });
          y -= 15;
        }

        // Horizontal line
        page.drawLine({
          start: { x: margin, y },
          end: { x: width - margin, y },
          thickness: 2,
          color: secondaryColor,
        });
        y -= 40;

        // Date and reference
        page.drawText(`Date: ${data.issueDate || "Date"}`, {
          x: width - margin - 150,
          y,
          size: 11,
          font: helveticaFont,
          color: secondaryColor,
        });
        y -= 15;

        if (data.referenceNumber) {
          page.drawText(`Ref: ${data.referenceNumber}`, {
            x: width - margin - 150,
            y,
            size: 11,
            font: helveticaFont,
            color: secondaryColor,
          });
        }
        y -= 40;

        // Recipient
        page.drawText("To Whom It May Concern", {
          x: margin,
          y,
          size: 11,
          font: helveticaFont,
          color: secondaryColor,
        });
        y -= 30;

        // Subject
        const subject = `Subject: Employment Verification for ${data.employeeName || "Employee"}`;
        page.drawText(subject, {
          x: margin,
          y,
          size: 11,
          font: helveticaBold,
          color: secondaryColor,
        });
        y -= 40;

        // Body paragraphs
        const paragraphs = [
          `This letter confirms that ${data.employeeName || "Employee"} is employed with ${companyName} as a ${data.employeeTitle || "Position"} in the ${data.department || "Department"} department.`,
          `Employment Start Date: ${data.startDate || "Date"}`,
          `Employment Type: ${data.employmentType || "Type"}`,
          `This letter is issued at the request of the employee${data.purpose ? ` for ${data.purpose}` : ""}.`,
          "If you require any additional information, please contact our HR department.",
        ];

        for (const para of paragraphs) {
          // Word wrap
          const words = para.split(" ");
          let line = "";
          const maxWidth = width - 2 * margin;

          for (const word of words) {
            const testLine = line + (line ? " " : "") + word;
            const testWidth = helveticaFont.widthOfTextAtSize(testLine, 11);

            if (testWidth > maxWidth && line) {
              page.drawText(line, { x: margin, y, size: 11, font: helveticaFont, color: secondaryColor });
              y -= 18;
              line = word;
            } else {
              line = testLine;
            }
          }
          if (line) {
            page.drawText(line, { x: margin, y, size: 11, font: helveticaFont, color: secondaryColor });
            y -= 30;
          }
        }
        y -= 20;

        // Signature
        page.drawText("Sincerely,", {
          x: margin,
          y,
          size: 11,
          font: helveticaFont,
          color: secondaryColor,
        });
        y -= 60;

        page.drawText(String(data.issuerName || "Name"), {
          x: margin,
          y,
          size: 11,
          font: helveticaBold,
          color: secondaryColor,
        });
        y -= 15;
        page.drawText(String(data.issuerTitle || "Title"), {
          x: margin,
          y,
          size: 11,
          font: helveticaFont,
          color: secondaryColor,
        });
        break;
      }

      case "case_bundle_cover": {
        // Cover page for case bundle
        y = height / 2 + 150;

        const companyName = String(data.companyName || "Company");
        const companyWidth = helveticaBold.widthOfTextAtSize(companyName, 24);
        page.drawText(companyName, {
          x: (width - companyWidth) / 2,
          y,
          size: 24,
          font: helveticaBold,
          color: primaryColor,
        });
        y -= 80;

        const title = "Case Documentation Bundle";
        const titleWidth = helveticaBold.widthOfTextAtSize(title, 28);
        page.drawText(title, {
          x: (width - titleWidth) / 2,
          y,
          size: 28,
          font: helveticaBold,
          color: secondaryColor,
        });
        y -= 40;

        const caseTitle = String(data.caseTitle || "Case");
        const caseTitleWidth = helveticaFont.widthOfTextAtSize(caseTitle, 18);
        page.drawText(caseTitle, {
          x: (width - caseTitleWidth) / 2,
          y,
          size: 18,
          font: helveticaFont,
          color: grayColor,
        });
        y -= 80;

        // Details
        const details = [
          ["Case Number:", String(data.caseNumber || "")],
          ["Case Type:", String(data.caseType || "")],
          ["Employee:", String(data.employeeName || "")],
          ["Generated By:", String(data.generatedBy || "")],
          ["Generated At:", String(data.generatedAt || "")],
        ];

        for (const [label, value] of details) {
          page.drawText(label, { x: margin + 100, y, size: 11, font: helveticaBold, color: secondaryColor });
          page.drawText(value, { x: margin + 220, y, size: 11, font: helveticaFont, color: secondaryColor });
          y -= 20;
        }
        y -= 80;

        // Confidential notice
        const confText = "CONFIDENTIAL - FOR AUTHORIZED PERSONNEL ONLY";
        const confWidth = helveticaBold.widthOfTextAtSize(confText, 14);
        page.drawText(confText, {
          x: (width - confWidth) / 2,
          y,
          size: 14,
          font: helveticaBold,
          color: rgb(0.9, 0.24, 0.24), // Red
        });
        break;
      }

      default: {
        // Default simple document
        const title = String(data.title || "Document");
        page.drawText(title, {
          x: margin,
          y,
          size: 18,
          font: helveticaBold,
          color: primaryColor,
        });
        y -= 40;

        const content = String(data.content || "");
        // Simple word wrap
        const words = content.split(" ");
        let line = "";
        const maxWidth = width - 2 * margin;

        for (const word of words) {
          const testLine = line + (line ? " " : "") + word;
          const testWidth = helveticaFont.widthOfTextAtSize(testLine, 11);

          if (testWidth > maxWidth && line) {
            page.drawText(line, { x: margin, y, size: 11, font: helveticaFont, color: secondaryColor });
            y -= 16;
            line = word;
          } else {
            line = testLine;
          }
        }
        if (line) {
          page.drawText(line, { x: margin, y, size: 11, font: helveticaFont, color: secondaryColor });
        }
        break;
      }
    }

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  }

  async merge(pdfs: Buffer[]): Promise<Buffer> {
    const { PDFDocument } = await import("pdf-lib");

    const mergedPdf = await PDFDocument.create();

    for (const pdfBuffer of pdfs) {
      try {
        const pdf = await PDFDocument.load(pdfBuffer);
        const pages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
        pages.forEach((page) => mergedPdf.addPage(page));
      } catch (error) {
        console.error("[HtmlPdfGenerator] Failed to merge PDF:", error);
        // Skip invalid PDFs
      }
    }

    const pdfBytes = await mergedPdf.save();
    return Buffer.from(pdfBytes);
  }
}

// =============================================================================
// PDF Templates
// =============================================================================

/**
 * HTML templates for PDF generation
 */
const PDF_TEMPLATES: Record<string, string> = {
  // Certificate template
  certificate: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: 'Georgia', serif;
      margin: 0;
      padding: 40px;
      text-align: center;
    }
    .certificate {
      border: 3px double #c9a227;
      padding: 40px;
      margin: 20px;
    }
    .header {
      font-size: 36px;
      color: #1a365d;
      margin-bottom: 20px;
    }
    .company-name {
      font-size: 24px;
      color: #2d3748;
      margin-bottom: 30px;
    }
    .certifies {
      font-size: 18px;
      color: #4a5568;
      margin: 20px 0;
    }
    .recipient-name {
      font-size: 32px;
      color: #1a365d;
      font-weight: bold;
      margin: 20px 0;
      border-bottom: 2px solid #c9a227;
      padding-bottom: 10px;
    }
    .course-name {
      font-size: 24px;
      color: #2d3748;
      margin: 30px 0;
    }
    .date {
      font-size: 16px;
      color: #718096;
      margin-top: 30px;
    }
    .signature {
      margin-top: 50px;
    }
    .signature-line {
      border-top: 1px solid #2d3748;
      width: 200px;
      margin: 0 auto;
      padding-top: 10px;
    }
  </style>
</head>
<body>
  <div class="certificate">
    <div class="company-name">{{companyName}}</div>
    <div class="header">Certificate of Completion</div>
    <div class="certifies">This certifies that</div>
    <div class="recipient-name">{{employeeName}}</div>
    <div class="certifies">has successfully completed</div>
    <div class="course-name">{{courseName}}</div>
    <div class="date">Completed on {{completionDate}}</div>
    <div class="signature">
      <div class="signature-line">{{issuerName}}, {{issuerTitle}}</div>
    </div>
  </div>
</body>
</html>
  `,

  // Employment letter template
  employment_letter: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 40px;
      line-height: 1.6;
    }
    .letterhead {
      text-align: center;
      border-bottom: 2px solid #2d3748;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .company-name {
      font-size: 24px;
      font-weight: bold;
      color: #1a365d;
    }
    .company-address {
      font-size: 12px;
      color: #718096;
    }
    .date {
      text-align: right;
      margin-bottom: 30px;
    }
    .reference {
      margin-bottom: 20px;
    }
    .recipient {
      margin-bottom: 20px;
    }
    .subject {
      font-weight: bold;
      margin-bottom: 20px;
    }
    .body {
      margin-bottom: 30px;
    }
    .signature {
      margin-top: 50px;
    }
    .signature-name {
      margin-top: 50px;
      font-weight: bold;
    }
  </style>
</head>
<body>
  <div class="letterhead">
    <div class="company-name">{{companyName}}</div>
    <div class="company-address">{{companyAddress}}</div>
  </div>

  <div class="date">Date: {{issueDate}}</div>
  <div class="reference">Ref: {{referenceNumber}}</div>

  <div class="recipient">
    To Whom It May Concern
  </div>

  <div class="subject">
    Subject: Employment Verification for {{employeeName}}
  </div>

  <div class="body">
    <p>This letter confirms that <strong>{{employeeName}}</strong> is employed with {{companyName}} as a <strong>{{employeeTitle}}</strong> in the {{department}} department.</p>

    <p>Employment Start Date: {{startDate}}</p>
    <p>Employment Type: {{employmentType}}</p>

    <p>This letter is issued at the request of the employee for {{purpose}}.</p>

    <p>If you require any additional information, please contact our HR department.</p>
  </div>

  <div class="signature">
    <p>Sincerely,</p>
    <div class="signature-name">
      {{issuerName}}<br>
      {{issuerTitle}}
    </div>
  </div>
</body>
</html>
  `,

  // Case bundle cover page
  case_bundle_cover: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 0;
      padding: 40px;
    }
    .cover {
      text-align: center;
      margin-top: 100px;
    }
    .company-name {
      font-size: 28px;
      font-weight: bold;
      color: #1a365d;
      margin-bottom: 50px;
    }
    .title {
      font-size: 36px;
      font-weight: bold;
      color: #2d3748;
      margin-bottom: 30px;
    }
    .subtitle {
      font-size: 24px;
      color: #4a5568;
      margin-bottom: 50px;
    }
    .details {
      text-align: left;
      margin: 50px auto;
      max-width: 400px;
    }
    .detail-row {
      margin: 10px 0;
    }
    .label {
      font-weight: bold;
      color: #2d3748;
    }
    .confidential {
      color: #e53e3e;
      font-size: 18px;
      font-weight: bold;
      margin-top: 100px;
    }
  </style>
</head>
<body>
  <div class="cover">
    <div class="company-name">{{companyName}}</div>
    <div class="title">Case Documentation Bundle</div>
    <div class="subtitle">{{caseTitle}}</div>

    <div class="details">
      <div class="detail-row"><span class="label">Case Number:</span> {{caseNumber}}</div>
      <div class="detail-row"><span class="label">Case Type:</span> {{caseType}}</div>
      <div class="detail-row"><span class="label">Employee:</span> {{employeeName}}</div>
      <div class="detail-row"><span class="label">Generated By:</span> {{generatedBy}}</div>
      <div class="detail-row"><span class="label">Generated At:</span> {{generatedAt}}</div>
    </div>

    <div class="confidential">CONFIDENTIAL - FOR AUTHORIZED PERSONNEL ONLY</div>
  </div>
</body>
</html>
  `,

  // Default template
  default: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 40px;
      line-height: 1.6;
    }
    .content {
      padding: 20px;
    }
  </style>
</head>
<body>
  <div class="content">
    <h1>{{title}}</h1>
    <p>{{content}}</p>
  </div>
</body>
</html>
  `,
};

// =============================================================================
// Document Storage
// =============================================================================

/**
 * Document storage interface
 */
export interface DocumentStorage {
  save(filename: string, content: Buffer): Promise<string>;
  getDownloadUrl(filePath: string, expiresIn?: number): Promise<string>;
  delete(filePath: string): Promise<void>;
}

/**
 * Local document storage
 */
export class LocalDocumentStorage implements DocumentStorage {
  private basePath: string;
  private baseUrl: string;

  constructor() {
    this.basePath = process.env["PDF_STORAGE_PATH"] || "/tmp/staffora-documents";
    this.baseUrl = process.env["PDF_BASE_URL"] || "http://localhost:3000/api/documents";
  }

  async save(filename: string, content: Buffer): Promise<string> {
    const fs = await import("fs/promises");
    const path = await import("path");

    await fs.mkdir(this.basePath, { recursive: true });
    const filePath = path.join(this.basePath, filename);
    await fs.writeFile(filePath, content);

    return filePath;
  }

  async getDownloadUrl(filePath: string, _expiresIn?: number): Promise<string> {
    const path = await import("path");
    const filename = path.basename(filePath);
    return `${this.baseUrl}/${filename}`;
  }

  async delete(filePath: string): Promise<void> {
    const fs = await import("fs/promises");
    try {
      await fs.unlink(filePath);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
        throw error;
      }
    }
  }
}

/**
 * Get document storage
 */
function getDocumentStorage(): DocumentStorage {
  return new LocalDocumentStorage();
}

/**
 * Get PDF generator
 */
function getPdfGenerator(): PdfGenerator {
  return new HtmlPdfGenerator();
}

// =============================================================================
// Certificate Processor
// =============================================================================

/**
 * Process certificate generation job
 */
async function processCertificate(
  payload: JobPayload<CertificatePayload>,
  context: JobContext
): Promise<void> {
  const { log, db, redis } = context;
  const { data, template, notifyUserId } = payload.data;

  log.info(`Generating certificate for ${data.employeeName}`);

  try {
    // Generate PDF
    const generator = getPdfGenerator();
    const pdfBuffer = await generator.generate(template || "certificate", data);

    // Save to storage
    const storage = getDocumentStorage();
    const filename = `certificate_${payload.id}_${data.employeeId}.pdf`;
    const filePath = await storage.save(filename, pdfBuffer);
    const downloadUrl = await storage.getDownloadUrl(filePath, 86400 * 7);

    // Save document record
    await saveDocumentRecord(db, {
      id: payload.id,
      tenantId: payload.tenantId!,
      userId: data.employeeId,
      documentType: "certificate",
      title: `Certificate: ${data.courseName}`,
      filePath,
      fileSize: pdfBuffer.length,
      metadata: {
        courseId: data.courseId,
        courseName: data.courseName,
        completionDate: data.completionDate,
        certificateNumber: data.certificateNumber,
      },
    });

    log.info("Certificate generated successfully", { downloadUrl });

    // Notify user
    if (notifyUserId && payload.tenantId) {
      await notifyDocumentReady(redis, {
        tenantId: payload.tenantId,
        userId: notifyUserId,
        documentId: payload.id,
        documentType: "certificate",
        title: `Certificate: ${data.courseName}`,
        downloadUrl,
      });
    }
  } catch (error) {
    log.error("Certificate generation failed", error);
    throw error;
  }
}

// =============================================================================
// Employment Letter Processor
// =============================================================================

/**
 * Process employment letter generation job
 */
async function processEmploymentLetter(
  payload: JobPayload<EmploymentLetterPayload>,
  context: JobContext
): Promise<void> {
  const { log, db, redis } = context;
  const { data, template, notifyUserId } = payload.data;

  log.info(`Generating employment letter for ${data.employeeName}`);

  try {
    // Generate PDF
    const generator = getPdfGenerator();
    const pdfBuffer = await generator.generate(template || "employment_letter", data);

    // Save to storage
    const storage = getDocumentStorage();
    const filename = `employment_letter_${payload.id}_${data.employeeId}.pdf`;
    const filePath = await storage.save(filename, pdfBuffer);
    const downloadUrl = await storage.getDownloadUrl(filePath, 86400 * 7);

    // Save document record
    await saveDocumentRecord(db, {
      id: payload.id,
      tenantId: payload.tenantId!,
      userId: data.employeeId,
      documentType: "employment_letter",
      title: `Employment ${data.letterType.charAt(0).toUpperCase() + data.letterType.slice(1)} Letter`,
      filePath,
      fileSize: pdfBuffer.length,
      metadata: {
        letterType: data.letterType,
        issueDate: data.issueDate,
        referenceNumber: data.referenceNumber,
      },
    });

    log.info("Employment letter generated successfully", { downloadUrl });

    // Notify user
    if (notifyUserId && payload.tenantId) {
      await notifyDocumentReady(redis, {
        tenantId: payload.tenantId,
        userId: notifyUserId,
        documentId: payload.id,
        documentType: "employment_letter",
        title: `Employment ${data.letterType} Letter`,
        downloadUrl,
      });
    }
  } catch (error) {
    log.error("Employment letter generation failed", error);
    throw error;
  }
}

// =============================================================================
// Case Bundle Processor
// =============================================================================

/**
 * Process case bundle generation job
 */
async function processCaseBundle(
  payload: JobPayload<CaseBundlePayload>,
  context: JobContext
): Promise<void> {
  const { log, db, redis } = context;
  const { data, template, notifyUserId } = payload.data;

  log.info(`Generating case bundle for case ${data.caseNumber}`);

  try {
    const generator = getPdfGenerator();
    const pdfs: Buffer[] = [];

    // Generate cover page
    const coverPdf = await generator.generate(template || "case_bundle_cover", data);
    pdfs.push(coverPdf);

    // Generate each document section
    for (const doc of data.documents) {
      if (doc.content) {
        const docPdf = await generator.generate("default", {
          title: doc.title,
          content: doc.content,
        });
        pdfs.push(docPdf);
      }

      // Fetch and include attachments if available
      if (doc.attachmentId && payload.tenantId) {
        const attachment = await fetchAttachment(db, payload.tenantId, doc.attachmentId);
        if (attachment && attachment.contentType === "application/pdf") {
          // If attachment is a PDF, include it directly
          pdfs.push(attachment.content);
        } else if (attachment) {
          // For non-PDF attachments, create a placeholder page
          const placeholderPdf = await generator.generate("default", {
            title: doc.title,
            content: `[Attachment: ${attachment.filename}]\n\nFile type: ${attachment.contentType}\nSize: ${attachment.size} bytes\n\nNote: This attachment could not be embedded in the PDF bundle.`,
          });
          pdfs.push(placeholderPdf);
        }
      }
    }

    // Generate timeline section if present
    if (data.timeline && data.timeline.length > 0) {
      const timelineHtml = data.timeline
        .map((t) => `<p><strong>${t.date}</strong>: ${t.event} - ${t.description || ""}</p>`)
        .join("");

      const timelinePdf = await generator.generate("default", {
        title: "Timeline of Events",
        content: timelineHtml,
      });
      pdfs.push(timelinePdf);
    }

    // Merge all PDFs
    let finalPdf: Buffer;
    if (generator.merge && pdfs.length > 1) {
      finalPdf = await generator.merge(pdfs);
    } else {
      finalPdf = pdfs[0] || Buffer.from("%PDF-1.4 empty", "utf-8");
    }

    // Save to storage
    const storage = getDocumentStorage();
    const filename = `case_bundle_${payload.id}_${data.caseId}.pdf`;
    const filePath = await storage.save(filename, finalPdf);
    const downloadUrl = await storage.getDownloadUrl(filePath, 86400 * 30); // 30 days

    // Save document record
    await saveDocumentRecord(db, {
      id: payload.id,
      tenantId: payload.tenantId!,
      userId: data.generatedBy,
      documentType: "case_bundle",
      title: `Case Bundle: ${data.caseNumber}`,
      filePath,
      fileSize: finalPdf.length,
      metadata: {
        caseId: data.caseId,
        caseNumber: data.caseNumber,
        caseType: data.caseType,
        documentCount: data.documents.length,
      },
    });

    log.info("Case bundle generated successfully", { downloadUrl });

    // Notify user
    if (notifyUserId && payload.tenantId) {
      await notifyDocumentReady(redis, {
        tenantId: payload.tenantId,
        userId: notifyUserId,
        documentId: payload.id,
        documentType: "case_bundle",
        title: `Case Bundle: ${data.caseNumber}`,
        downloadUrl,
      });
    }
  } catch (error) {
    log.error("Case bundle generation failed", error);
    throw error;
  }
}

// =============================================================================
// Database Operations
// =============================================================================

async function fetchAttachment(
  db: import("../plugins/db").DatabaseClient,
  tenantId: string,
  attachmentId: string
): Promise<
  | {
      filename: string;
      contentType: string;
      size: number;
      content: Buffer;
    }
  | null
> {
  return await db.withSystemContext(async (tx) => {
    const rows = await tx<
      Array<{
        fileName: string;
        fileSizeBytes: number;
        mimeType: string;
        storageProvider: string;
        storageKey: string;
      }>
    >`
      SELECT
        file_name as "fileName",
        file_size_bytes as "fileSizeBytes",
        mime_type as "mimeType",
        storage_provider as "storageProvider",
        storage_key as "storageKey"
      FROM app.case_attachments
      WHERE tenant_id = ${tenantId}::uuid
        AND id = ${attachmentId}::uuid
        AND deleted_at IS NULL
      LIMIT 1
    `;

    const row = rows[0];
    if (!row) return null;

    if (row.storageProvider !== "local") {
      return null;
    }

    const fs = await import("fs/promises");
    const content = await fs.readFile(row.storageKey);

    return {
      filename: row.fileName,
      contentType: row.mimeType,
      size: row.fileSizeBytes,
      content,
    };
  });
}

/**
 * Save document record to database
 */
async function saveDocumentRecord(
  db: import("../plugins/db").DatabaseClient,
  record: {
    id: string;
    tenantId: string;
    userId: string;
    documentType: PdfDocumentType;
    title: string;
    filePath: string;
    fileSize: number;
    metadata: Record<string, unknown>;
  }
): Promise<void> {
  await db.withSystemContext(async (tx) => {
    await tx`
      INSERT INTO app.documents (
        id,
        tenant_id,
        user_id,
        document_type,
        title,
        file_path,
        file_size,
        metadata,
        created_at
      )
      VALUES (
        ${record.id}::uuid,
        ${record.tenantId}::uuid,
        ${record.userId}::uuid,
        ${record.documentType},
        ${record.title},
        ${record.filePath},
        ${record.fileSize},
        ${JSON.stringify(record.metadata)}::jsonb,
        now()
      )
    `;
  });
}

/**
 * Notify user that document is ready
 */
async function notifyDocumentReady(
  redis: import("ioredis").default,
  notification: {
    tenantId: string;
    userId: string;
    documentId: string;
    documentType: PdfDocumentType;
    title: string;
    downloadUrl: string;
  }
): Promise<void> {
  await redis.xadd(
    StreamKeys.NOTIFICATIONS,
    "*",
    "payload",
    JSON.stringify({
      id: crypto.randomUUID(),
      type: "notification.in_app",
      tenantId: notification.tenantId,
      userId: notification.userId,
      data: {
        userId: notification.userId,
        title: "Document Ready",
        message: `Your document "${notification.title}" is ready for download.`,
        type: "document_ready",
        actionUrl: notification.downloadUrl,
        actionText: "Download",
        data: {
          documentId: notification.documentId,
          documentType: notification.documentType,
        },
      },
      metadata: {
        createdAt: new Date().toISOString(),
      },
    }),
    "attempt",
    "1"
  );
}

// =============================================================================
// Processor Registrations
// =============================================================================

/**
 * Certificate processor registration
 */
export const certificateProcessor: ProcessorRegistration<CertificatePayload> = {
  type: JobTypes.PDF_CERTIFICATE,
  processor: processCertificate,
  timeoutMs: 120000, // 2 minutes
  retry: true,
};

/**
 * Employment letter processor registration
 */
export const employmentLetterProcessor: ProcessorRegistration<EmploymentLetterPayload> = {
  type: JobTypes.PDF_EMPLOYMENT_LETTER,
  processor: processEmploymentLetter,
  timeoutMs: 120000, // 2 minutes
  retry: true,
};

/**
 * Case bundle processor registration
 */
export const caseBundleProcessor: ProcessorRegistration<CaseBundlePayload> = {
  type: JobTypes.PDF_CASE_BUNDLE,
  processor: processCaseBundle,
  timeoutMs: 300000, // 5 minutes (bundles can be large)
  retry: true,
};

// =============================================================================
// Bulk Document Generation Item Processor
// =============================================================================

/**
 * Payload for a single bulk document generation item.
 * Matches the shape written by the domain event handler.
 */
export interface BulkDocumentItemPayload {
  batchId: string;
  batchItemId: string;
  templateId: string;
  templateName: string;
  employeeId: string;
  variables: Record<string, string>;
}

/**
 * Process a single employee's document generation within a bulk batch.
 *
 * Flow:
 * 1. Mark the batch item as 'processing'
 * 2. Load the letter template and employee data
 * 3. Render the template with merged placeholder values
 * 4. Create a generated_letters record
 * 5. Mark the batch item as 'completed' with the generated letter ID
 * 6. Update batch counters
 * 7. If all items processed, finalize the batch status
 */
async function processBulkDocumentItem(
  payload: JobPayload<BulkDocumentItemPayload>,
  context: JobContext
): Promise<void> {
  const { log, db } = context;
  const { batchId, batchItemId, templateId, employeeId, variables } = payload.data;
  const tenantId = payload.tenantId!;

  log.info("Processing bulk document generation item", {
    batchId,
    batchItemId,
    employeeId,
  });

  try {
    // Mark item as processing
    await db.withSystemContext(async (tx) => {
      await tx`
        UPDATE app.document_generation_batch_items
        SET status = 'processing', started_at = now()
        WHERE id = ${batchItemId}::uuid
      `;
    });

    // Load template
    const template = await db.withSystemContext(async (tx) => {
      const rows = await tx<Array<{
        id: string;
        name: string;
        subject: string | null;
        bodyTemplate: string;
        placeholders: unknown[];
        active: boolean;
      }>>`
        SELECT id, name, subject, body_template, placeholders, active
        FROM app.letter_templates
        WHERE id = ${templateId}::uuid
          AND tenant_id = ${tenantId}::uuid
      `;
      return rows[0] ?? null;
    });

    if (!template) {
      throw new Error(`Letter template ${templateId} not found`);
    }

    if (!template.active) {
      throw new Error(`Letter template ${templateId} is inactive`);
    }

    // Load employee data for placeholder rendering
    const employeeData = await db.withSystemContext(async (tx) => {
      const rows = await tx<Record<string, unknown>[]>`
        SELECT
          e.id,
          e.employee_number,
          e.status,
          e.hire_date,
          ep.first_name,
          ep.last_name,
          ep.middle_name,
          ep.preferred_name,
          ep.date_of_birth,
          ep.gender,
          ep.nationality,
          ec.contract_type,
          ec.employment_type,
          ec.fte,
          ec.working_hours_per_week,
          ec.probation_end_date,
          ec.notice_period_days,
          p.title    AS position_title,
          p.code     AS position_code,
          ou.name    AS org_unit_name,
          ou.code    AS org_unit_code,
          comp.base_salary,
          comp.currency,
          comp.pay_frequency,
          mgr_personal.first_name AS manager_first_name,
          mgr_personal.last_name  AS manager_last_name,
          mgr_emp.employee_number AS manager_employee_number
        FROM app.employees e
        LEFT JOIN app.employee_personal ep
          ON ep.employee_id = e.id AND ep.effective_to IS NULL
        LEFT JOIN app.employee_contracts ec
          ON ec.employee_id = e.id AND ec.effective_to IS NULL
        LEFT JOIN app.position_assignments pa
          ON pa.employee_id = e.id AND pa.effective_to IS NULL AND pa.is_primary = true
        LEFT JOIN app.positions p
          ON p.id = pa.position_id
        LEFT JOIN app.org_units ou
          ON ou.id = pa.org_unit_id
        LEFT JOIN app.compensation comp
          ON comp.employee_id = e.id AND comp.effective_to IS NULL
        LEFT JOIN app.reporting_lines rl
          ON rl.employee_id = e.id AND rl.effective_to IS NULL AND rl.is_primary = true
        LEFT JOIN app.employees mgr_emp
          ON mgr_emp.id = rl.manager_id
        LEFT JOIN app.employee_personal mgr_personal
          ON mgr_personal.employee_id = mgr_emp.id AND mgr_personal.effective_to IS NULL
        WHERE e.id = ${employeeId}::uuid
          AND e.tenant_id = ${tenantId}::uuid
      `;
      return rows[0] ?? null;
    });

    if (!employeeData) {
      throw new Error(`Employee ${employeeId} not found`);
    }

    // Build flat string map for template rendering
    const safeStr = (val: unknown): string => {
      if (val === null || val === undefined) return "";
      if (val instanceof Date) return val.toISOString().split("T")[0]!;
      return String(val);
    };

    const autoValues: Record<string, string> = {
      employee_number: safeStr(employeeData.employeeNumber),
      first_name: safeStr(employeeData.firstName),
      last_name: safeStr(employeeData.lastName),
      full_name: [employeeData.firstName, employeeData.lastName].filter(Boolean).join(" "),
      middle_name: safeStr(employeeData.middleName),
      preferred_name: safeStr(employeeData.preferredName),
      date_of_birth: safeStr(employeeData.dateOfBirth),
      gender: safeStr(employeeData.gender),
      nationality: safeStr(employeeData.nationality),
      hire_date: safeStr(employeeData.hireDate),
      status: safeStr(employeeData.status),
      contract_type: safeStr(employeeData.contractType),
      employment_type: safeStr(employeeData.employmentType),
      fte: safeStr(employeeData.fte),
      working_hours_per_week: safeStr(employeeData.workingHoursPerWeek),
      probation_end_date: safeStr(employeeData.probationEndDate),
      notice_period_days: safeStr(employeeData.noticePeriodDays),
      position_title: safeStr(employeeData.positionTitle),
      position_code: safeStr(employeeData.positionCode),
      org_unit_name: safeStr(employeeData.orgUnitName),
      org_unit_code: safeStr(employeeData.orgUnitCode),
      base_salary: safeStr(employeeData.baseSalary),
      currency: safeStr(employeeData.currency),
      pay_frequency: safeStr(employeeData.payFrequency),
      manager_name: [employeeData.managerFirstName, employeeData.managerLastName].filter(Boolean).join(" "),
      manager_employee_number: safeStr(employeeData.managerEmployeeNumber),
      today_date: new Date().toISOString().split("T")[0]!,
      current_year: String(new Date().getFullYear()),
    };

    // Merge: explicit variables override auto-resolved employee data
    const mergedValues: Record<string, string> = {
      ...autoValues,
      ...variables,
    };

    // Render template
    const renderTemplate = (tpl: string, values: Record<string, string>): string => {
      return tpl.replace(/\{\{(\w+)\}\}/g, (_match, key: string) => {
        return values[key] !== undefined ? values[key] : `{{${key}}}`;
      });
    };

    const renderedSubject = template.subject
      ? renderTemplate(template.subject, mergedValues)
      : null;
    const renderedBody = renderTemplate(template.bodyTemplate, mergedValues);

    // Create generated letter and update batch item atomically
    await db.withSystemContext(async (tx) => {
      // Create generated letter
      const letterRows = await tx<Array<{ id: string }>>`
        INSERT INTO app.generated_letters (
          tenant_id, template_id, employee_id, generated_by,
          subject, body, placeholders_used
        )
        VALUES (
          ${tenantId}::uuid,
          ${templateId}::uuid,
          ${employeeId}::uuid,
          ${payload.userId || "system"}::uuid,
          ${renderedSubject},
          ${renderedBody},
          ${JSON.stringify(mergedValues)}::jsonb
        )
        RETURNING id
      `;

      const generatedLetterId = letterRows[0]!.id;

      // Mark batch item as completed
      await tx`
        UPDATE app.document_generation_batch_items
        SET
          status = 'completed',
          generated_letter_id = ${generatedLetterId}::uuid,
          completed_at = now()
        WHERE id = ${batchItemId}::uuid
      `;

      // Increment completed count on the batch
      await tx`
        UPDATE app.document_generation_batches
        SET completed_items = completed_items + 1, updated_at = now()
        WHERE id = ${batchId}::uuid
      `;

      // Check if all items are done and finalize batch
      await tx`
        UPDATE app.document_generation_batches
        SET
          status = CASE
            WHEN completed_items + failed_items = total_items AND failed_items = 0 THEN 'completed'
            WHEN completed_items + failed_items = total_items AND completed_items > 0 AND failed_items > 0 THEN 'completed_with_errors'
            WHEN completed_items + failed_items = total_items AND failed_items = total_items THEN 'failed'
            ELSE 'processing'
          END,
          updated_at = now()
        WHERE id = ${batchId}::uuid
      `;

      // Write outbox event for completed item
      await tx`
        INSERT INTO app.domain_outbox (
          id, tenant_id, aggregate_type, aggregate_id,
          event_type, payload, created_at
        )
        VALUES (
          gen_random_uuid(),
          ${tenantId}::uuid,
          'document_generation_batch_item',
          ${batchItemId}::uuid,
          'documents.bulk_generation.item_completed',
          ${JSON.stringify({
            batchId,
            batchItemId,
            employeeId,
            generatedLetterId,
            actor: payload.userId,
          })}::jsonb,
          now()
        )
      `;

      log.info("Bulk document item generated successfully", {
        batchItemId,
        employeeId,
        generatedLetterId,
      });
    });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    log.error("Bulk document item generation failed", error, {
      batchItemId,
      employeeId,
    });

    // Mark item as failed and update batch counters
    await db.withSystemContext(async (tx) => {
      await tx`
        UPDATE app.document_generation_batch_items
        SET
          status = 'failed',
          error_message = ${errorMessage},
          completed_at = now()
        WHERE id = ${batchItemId}::uuid
      `;

      await tx`
        UPDATE app.document_generation_batches
        SET failed_items = failed_items + 1, updated_at = now()
        WHERE id = ${batchId}::uuid
      `;

      // Check if all items are done and finalize batch
      await tx`
        UPDATE app.document_generation_batches
        SET
          status = CASE
            WHEN completed_items + failed_items = total_items AND failed_items = 0 THEN 'completed'
            WHEN completed_items + failed_items = total_items AND completed_items > 0 AND failed_items > 0 THEN 'completed_with_errors'
            WHEN completed_items + failed_items = total_items AND failed_items = total_items THEN 'failed'
            ELSE 'processing'
          END,
          updated_at = now()
        WHERE id = ${batchId}::uuid
      `;
    });

    // Do NOT re-throw: we handled the failure by recording it in the batch item.
    // Re-throwing would cause the job framework to retry, creating duplicates.
  }
}

/**
 * Bulk document item processor registration
 */
export const bulkDocumentItemProcessor: ProcessorRegistration<BulkDocumentItemPayload> = {
  type: JobTypes.PDF_BULK_DOCUMENT_ITEM,
  processor: processBulkDocumentItem,
  timeoutMs: 120000, // 2 minutes per item
  retry: false, // Failures are tracked in the batch item table, not retried by the job framework
};

/**
 * All PDF processors
 */
export const pdfProcessors: ProcessorRegistration[] = [
  certificateProcessor,
  employmentLetterProcessor,
  caseBundleProcessor,
  bulkDocumentItemProcessor,
];

export default pdfProcessors;
