/**
 * State Machines
 *
 * Re-exports all state machine definitions and utilities.
 * State machines define valid states and transitions for key domain entities.
 */

// Employee lifecycle state machine
export {
  EmployeeStates,
  type EmployeeState,
  canTransition,
  getValidTransitions,
  getTransitionMetadata,
  getTransitionLabel,
  validateTransition,
  isTerminalState,
  isActiveEmployee,
  getInitialState,
  isEmployeeState,
  getStateMachineSummary,
  type TransitionMetadata,
  EMPLOYEE_TRANSITION_LABELS,
} from "./employee";

// Performance cycle state machine
export {
  PerformanceCycleStates,
  type PerformanceCycleState,
  canTransitionCycle,
  getValidCycleTransitions,
  getCycleTransitionMetadata,
  getCycleTransitionLabel,
  validateCycleTransition,
  isCycleTerminalState,
  isCycleInProgress,
  areRatingsLocked,
  areGoalsLocked,
  getCycleInitialState,
  isPerformanceCycleState,
  getPhaseInfo,
  getCycleStateMachineSummary,
  type CycleTransitionMetadata,
  type PhaseInfo,
  CYCLE_TRANSITION_LABELS,
  PHASE_INFO,
} from "./performance-cycle";

// Leave request state machine
export {
  LeaveRequestStates,
  type LeaveRequestState,
  canTransitionLeaveRequest,
  getValidLeaveRequestTransitions,
  getLeaveRequestTransitionMetadata,
  getLeaveRequestTransitionLabel,
  validateLeaveRequestTransition,
  isLeaveRequestTerminalState,
  leaveRequestRequiresAction,
  getLeaveRequestInitialState,
  isLeaveRequestState,
  getLeaveRequestStateMachineSummary,
  type LeaveTransitionMetadata,
  LEAVE_REQUEST_TRANSITION_LABELS,
} from "./leave-request";

// Case state machine
export {
  CaseStates,
  type CaseState,
  canTransitionCase,
  getValidCaseTransitions,
  getCaseTransitionMetadata,
  getCaseTransitionLabel,
  validateCaseTransition,
  isCaseTerminalState,
  isCaseActive,
  getCaseInitialState,
  isCaseState,
  getCaseStateMachineSummary,
  type CaseTransitionMetadata,
  CASE_TRANSITION_LABELS,
} from "./case";

// Flexible working state machine
export {
  FlexibleWorkingStates,
  type FlexibleWorkingState,
  canTransitionFlexibleWorking,
  getValidFlexibleWorkingTransitions,
  getFlexibleWorkingTransitionMetadata,
  getFlexibleWorkingTransitionLabel,
  validateFlexibleWorkingTransition,
  isFlexibleWorkingTerminalState,
  isFlexibleWorkingActive,
  isFlexibleWorkingState,
  getFlexibleWorkingInitialState,
  requiresConsultationBeforeRejection,
  isStatutoryRejectionGround,
  getFlexibleWorkingStateMachineSummary,
  type FlexibleWorkingTransitionMetadata,
  FLEXIBLE_WORKING_TRANSITION_LABELS,
  STATUTORY_REJECTION_GROUNDS,
  type StatutoryRejectionGround,
  REJECTION_GROUND_LABELS,
} from "./flexible-working";

// Data breach state machine
export {
  DataBreachStates,
  type DataBreachState,
  canTransitionDataBreach,
  getValidDataBreachTransitions,
  getDataBreachTransitionMetadata,
  getDataBreachTransitionLabel,
  validateDataBreachTransition,
  isDataBreachTerminalState,
  isDataBreachActive,
  isIcoNotificationPending,
  getDataBreachInitialState,
  isDataBreachState,
  getDataBreachStateMachineSummary,
  type DataBreachTransitionMetadata,
  DATA_BREACH_TRANSITION_LABELS,
} from "./data-breach";

// Workflow state machine
export {
  WorkflowStates,
  type WorkflowState,
  canTransitionWorkflow,
  getValidWorkflowTransitions,
  getWorkflowTransitionMetadata,
  getWorkflowTransitionLabel,
  validateWorkflowTransition,
  isWorkflowTerminalState,
  isWorkflowActive,
  workflowRequiresApproval,
  getWorkflowInitialState,
  isWorkflowState,
  getWorkflowStateMachineSummary,
  type WorkflowTransitionMetadata,
  WORKFLOW_TRANSITION_LABELS,
} from "./workflow";

// Onboarding state machines (template, instance, task)
export {
  OnboardingTemplateStates,
  type OnboardingTemplateState,
  canTransitionTemplate,
  getValidTemplateTransitions,
  getTemplateTransitionMetadata,
  getTemplateTransitionLabel,
  validateTemplateTransition,
  isTemplateTerminalState,
  isTemplateUsable,
  getTemplateInitialState,
  isOnboardingTemplateState,
  getTemplateStateMachineSummary,
  type TemplateTransitionMetadata,
  TEMPLATE_TRANSITION_LABELS,
  OnboardingInstanceStates,
  type OnboardingInstanceState,
  canTransitionInstance,
  getValidInstanceTransitions,
  getInstanceTransitionMetadata,
  getInstanceTransitionLabel,
  validateInstanceTransition,
  isInstanceTerminalState,
  isInstanceActive,
  getInstanceInitialState,
  isOnboardingInstanceState,
  getInstanceStateMachineSummary,
  type InstanceTransitionMetadata,
  INSTANCE_TRANSITION_LABELS,
  OnboardingTaskStates,
  type OnboardingTaskState,
  canTransitionTask,
  getValidTaskTransitions,
  getTaskTransitionMetadata,
  getTaskTransitionLabel,
  validateTaskTransition,
  isTaskTerminalState,
  isTaskActionable,
  getTaskInitialState,
  isOnboardingTaskState,
  getTaskStateMachineSummary,
  type TaskTransitionMetadata,
  TASK_TRANSITION_LABELS,
} from "./onboarding";

// Recruitment state machines (requisition, candidate stage, offer)
export {
  RequisitionStates,
  type RequisitionState,
  canTransitionRequisition,
  getValidRequisitionTransitions,
  getRequisitionTransitionMetadata,
  getRequisitionTransitionLabel,
  validateRequisitionTransition,
  isRequisitionTerminalState,
  isRequisitionActive,
  getRequisitionInitialState,
  isRequisitionState,
  getRequisitionStateMachineSummary,
  type RequisitionTransitionMetadata,
  REQUISITION_TRANSITION_LABELS,
  CandidateStages,
  type CandidateStage,
  canTransitionCandidateStage,
  getValidCandidateStageTransitions,
  getCandidateStageTransitionMetadata,
  getCandidateStageTransitionLabel,
  validateCandidateStageTransition,
  isCandidateStageTerminal,
  isCandidateActive,
  getCandidateInitialStage,
  isCandidateStage,
  getCandidateStageStateMachineSummary,
  type CandidateStageTransitionMetadata,
  CANDIDATE_STAGE_TRANSITION_LABELS,
  OfferStates,
  type OfferState,
  canTransitionOffer,
  getValidOfferTransitions,
  getOfferTransitionMetadata,
  getOfferTransitionLabel,
  validateOfferTransition,
  isOfferTerminalState,
  isOfferActive,
  getOfferInitialState,
  isOfferState,
  getOfferStateMachineSummary,
  type OfferTransitionMetadata,
  OFFER_TRANSITION_LABELS,
} from "./recruitment";
