// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/mfa": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/me": {
    params: {};
  };
  "/me/profile": {
    params: {};
  };
  "/me/time": {
    params: {};
  };
  "/me/leave": {
    params: {};
  };
  "/me/benefits": {
    params: {};
  };
  "/me/documents": {
    params: {};
  };
  "/me/learning": {
    params: {};
  };
  "/me/cases": {
    params: {};
  };
  "/me/competencies": {
    params: {};
  };
  "/me/onboarding": {
    params: {};
  };
  "/manager": {
    params: {};
  };
  "/manager/team": {
    params: {};
  };
  "/manager/approvals": {
    params: {};
  };
  "/manager/schedules": {
    params: {};
  };
  "/manager/performance": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/hr": {
    params: {};
  };
  "/admin/hr/employees": {
    params: {};
  };
  "/admin/hr/employees/:employeeId": {
    params: {
      "employeeId": string;
    };
  };
  "/admin/hr/positions": {
    params: {};
  };
  "/admin/hr/departments": {
    params: {};
  };
  "/admin/hr/organization": {
    params: {};
  };
  "/admin/hr/org-chart": {
    params: {};
  };
  "/admin/time": {
    params: {};
  };
  "/admin/time/timesheets": {
    params: {};
  };
  "/admin/time/schedules": {
    params: {};
  };
  "/admin/absence": {
    params: {};
  };
  "/admin/talent": {
    params: {};
  };
  "/admin/talent/performance": {
    params: {};
  };
  "/admin/talent/competencies": {
    params: {};
  };
  "/admin/talent/succession": {
    params: {};
  };
  "/admin/talent/recruitment": {
    params: {};
  };
  "/admin/talent/recruitment/candidates": {
    params: {};
  };
  "/admin/benefits": {
    params: {};
  };
  "/admin/cases": {
    params: {};
  };
  "/admin/cases/:caseId": {
    params: {
      "caseId": string;
    };
  };
  "/admin/onboarding": {
    params: {};
  };
  "/admin/onboarding/templates": {
    params: {};
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/workflows": {
    params: {};
  };
  "/admin/workflows/builder": {
    params: {};
  };
  "/admin/workflows/templates": {
    params: {};
  };
  "/admin/security": {
    params: {};
  };
  "/admin/security/users": {
    params: {};
  };
  "/admin/security/roles": {
    params: {};
  };
  "/admin/security/permissions": {
    params: {};
  };
  "/admin/security/audit-log": {
    params: {};
  };
  "/admin/reports": {
    params: {};
  };
  "/admin/reports/:reportId": {
    params: {
      "reportId": string;
    };
  };
  "/admin/lms": {
    params: {};
  };
  "/admin/lms/courses": {
    params: {};
  };
  "/admin/lms/assignments": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/settings/tenant": {
    params: {};
  };
  "/admin/settings/integrations": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/mfa" | "/forgot-password" | "/reset-password" | "/dashboard" | "/me" | "/me/profile" | "/me/time" | "/me/leave" | "/me/benefits" | "/me/documents" | "/me/learning" | "/me/cases" | "/me/competencies" | "/me/onboarding" | "/manager" | "/manager/team" | "/manager/approvals" | "/manager/schedules" | "/manager/performance" | "/admin/dashboard" | "/admin/hr" | "/admin/hr/employees" | "/admin/hr/employees/:employeeId" | "/admin/hr/positions" | "/admin/hr/departments" | "/admin/hr/organization" | "/admin/hr/org-chart" | "/admin/time" | "/admin/time/timesheets" | "/admin/time/schedules" | "/admin/absence" | "/admin/talent" | "/admin/talent/performance" | "/admin/talent/competencies" | "/admin/talent/succession" | "/admin/talent/recruitment" | "/admin/talent/recruitment/candidates" | "/admin/benefits" | "/admin/cases" | "/admin/cases/:caseId" | "/admin/onboarding" | "/admin/onboarding/templates" | "/admin/analytics" | "/admin/workflows" | "/admin/workflows/builder" | "/admin/workflows/templates" | "/admin/security" | "/admin/security/users" | "/admin/security/roles" | "/admin/security/permissions" | "/admin/security/audit-log" | "/admin/reports" | "/admin/reports/:reportId" | "/admin/lms" | "/admin/lms/courses" | "/admin/lms/assignments" | "/admin/settings" | "/admin/settings/tenant" | "/admin/settings/integrations" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/(auth)/layout.tsx": {
    id: "routes/(auth)/layout";
    page: "/login" | "/mfa" | "/forgot-password" | "/reset-password";
  };
  "routes/(auth)/login/route.tsx": {
    id: "routes/(auth)/login/route";
    page: "/login";
  };
  "routes/(auth)/mfa/route.tsx": {
    id: "routes/(auth)/mfa/route";
    page: "/mfa";
  };
  "routes/(auth)/forgot-password/route.tsx": {
    id: "routes/(auth)/forgot-password/route";
    page: "/forgot-password";
  };
  "routes/(auth)/reset-password/route.tsx": {
    id: "routes/(auth)/reset-password/route";
    page: "/reset-password";
  };
  "routes/(app)/layout.tsx": {
    id: "routes/(app)/layout";
    page: "/dashboard" | "/me" | "/me/profile" | "/me/time" | "/me/leave" | "/me/benefits" | "/me/documents" | "/me/learning" | "/me/cases" | "/me/competencies" | "/me/onboarding" | "/manager" | "/manager/team" | "/manager/approvals" | "/manager/schedules" | "/manager/performance";
  };
  "routes/(app)/dashboard/route.tsx": {
    id: "routes/(app)/dashboard/route";
    page: "/dashboard";
  };
  "routes/(app)/me/index.tsx": {
    id: "routes/(app)/me/index";
    page: "/me";
  };
  "routes/(app)/me/profile/route.tsx": {
    id: "routes/(app)/me/profile/route";
    page: "/me/profile";
  };
  "routes/(app)/me/time/route.tsx": {
    id: "routes/(app)/me/time/route";
    page: "/me/time";
  };
  "routes/(app)/me/leave/route.tsx": {
    id: "routes/(app)/me/leave/route";
    page: "/me/leave";
  };
  "routes/(app)/me/benefits/route.tsx": {
    id: "routes/(app)/me/benefits/route";
    page: "/me/benefits";
  };
  "routes/(app)/me/documents/route.tsx": {
    id: "routes/(app)/me/documents/route";
    page: "/me/documents";
  };
  "routes/(app)/me/learning/route.tsx": {
    id: "routes/(app)/me/learning/route";
    page: "/me/learning";
  };
  "routes/(app)/me/cases/route.tsx": {
    id: "routes/(app)/me/cases/route";
    page: "/me/cases";
  };
  "routes/(app)/me/competencies/route.tsx": {
    id: "routes/(app)/me/competencies/route";
    page: "/me/competencies";
  };
  "routes/(app)/me/onboarding/route.tsx": {
    id: "routes/(app)/me/onboarding/route";
    page: "/me/onboarding";
  };
  "routes/(app)/manager/index.tsx": {
    id: "routes/(app)/manager/index";
    page: "/manager";
  };
  "routes/(app)/manager/team/route.tsx": {
    id: "routes/(app)/manager/team/route";
    page: "/manager/team";
  };
  "routes/(app)/manager/approvals/route.tsx": {
    id: "routes/(app)/manager/approvals/route";
    page: "/manager/approvals";
  };
  "routes/(app)/manager/schedules/route.tsx": {
    id: "routes/(app)/manager/schedules/route";
    page: "/manager/schedules";
  };
  "routes/(app)/manager/performance/route.tsx": {
    id: "routes/(app)/manager/performance/route";
    page: "/manager/performance";
  };
  "routes/(admin)/layout.tsx": {
    id: "routes/(admin)/layout";
    page: "/admin/dashboard" | "/admin/hr" | "/admin/hr/employees" | "/admin/hr/employees/:employeeId" | "/admin/hr/positions" | "/admin/hr/departments" | "/admin/hr/organization" | "/admin/hr/org-chart" | "/admin/time" | "/admin/time/timesheets" | "/admin/time/schedules" | "/admin/absence" | "/admin/talent" | "/admin/talent/performance" | "/admin/talent/competencies" | "/admin/talent/succession" | "/admin/talent/recruitment" | "/admin/talent/recruitment/candidates" | "/admin/benefits" | "/admin/cases" | "/admin/cases/:caseId" | "/admin/onboarding" | "/admin/onboarding/templates" | "/admin/analytics" | "/admin/workflows" | "/admin/workflows/builder" | "/admin/workflows/templates" | "/admin/security" | "/admin/security/users" | "/admin/security/roles" | "/admin/security/permissions" | "/admin/security/audit-log" | "/admin/reports" | "/admin/reports/:reportId" | "/admin/lms" | "/admin/lms/courses" | "/admin/lms/assignments" | "/admin/settings" | "/admin/settings/tenant" | "/admin/settings/integrations";
  };
  "routes/(admin)/dashboard/route.tsx": {
    id: "routes/(admin)/dashboard/route";
    page: "/admin/dashboard";
  };
  "routes/(admin)/hr/index.tsx": {
    id: "routes/(admin)/hr/index";
    page: "/admin/hr";
  };
  "routes/(admin)/hr/employees/route.tsx": {
    id: "routes/(admin)/hr/employees/route";
    page: "/admin/hr/employees";
  };
  "routes/(admin)/hr/employees/[employeeId]/route.tsx": {
    id: "routes/(admin)/hr/employees/[employeeId]/route";
    page: "/admin/hr/employees/:employeeId";
  };
  "routes/(admin)/hr/positions/route.tsx": {
    id: "routes/(admin)/hr/positions/route";
    page: "/admin/hr/positions";
  };
  "routes/(admin)/hr/departments/route.tsx": {
    id: "routes/(admin)/hr/departments/route";
    page: "/admin/hr/departments";
  };
  "routes/(admin)/hr/organization/route.tsx": {
    id: "routes/(admin)/hr/organization/route";
    page: "/admin/hr/organization";
  };
  "routes/(admin)/hr/org-chart/route.tsx": {
    id: "routes/(admin)/hr/org-chart/route";
    page: "/admin/hr/org-chart";
  };
  "routes/(admin)/time/index.tsx": {
    id: "routes/(admin)/time/index";
    page: "/admin/time";
  };
  "routes/(admin)/time/timesheets/route.tsx": {
    id: "routes/(admin)/time/timesheets/route";
    page: "/admin/time/timesheets";
  };
  "routes/(admin)/time/schedules/route.tsx": {
    id: "routes/(admin)/time/schedules/route";
    page: "/admin/time/schedules";
  };
  "routes/(admin)/absence/index.tsx": {
    id: "routes/(admin)/absence/index";
    page: "/admin/absence";
  };
  "routes/(admin)/talent/index.tsx": {
    id: "routes/(admin)/talent/index";
    page: "/admin/talent";
  };
  "routes/(admin)/talent/performance/route.tsx": {
    id: "routes/(admin)/talent/performance/route";
    page: "/admin/talent/performance";
  };
  "routes/(admin)/talent/competencies/route.tsx": {
    id: "routes/(admin)/talent/competencies/route";
    page: "/admin/talent/competencies";
  };
  "routes/(admin)/talent/succession/route.tsx": {
    id: "routes/(admin)/talent/succession/route";
    page: "/admin/talent/succession";
  };
  "routes/(admin)/talent/recruitment/route.tsx": {
    id: "routes/(admin)/talent/recruitment/route";
    page: "/admin/talent/recruitment";
  };
  "routes/(admin)/talent/recruitment/candidates/route.tsx": {
    id: "routes/(admin)/talent/recruitment/candidates/route";
    page: "/admin/talent/recruitment/candidates";
  };
  "routes/(admin)/benefits/route.tsx": {
    id: "routes/(admin)/benefits/route";
    page: "/admin/benefits";
  };
  "routes/(admin)/cases/index.tsx": {
    id: "routes/(admin)/cases/index";
    page: "/admin/cases";
  };
  "routes/(admin)/cases/[caseId]/route.tsx": {
    id: "routes/(admin)/cases/[caseId]/route";
    page: "/admin/cases/:caseId";
  };
  "routes/(admin)/onboarding/index.tsx": {
    id: "routes/(admin)/onboarding/index";
    page: "/admin/onboarding";
  };
  "routes/(admin)/onboarding/templates/route.tsx": {
    id: "routes/(admin)/onboarding/templates/route";
    page: "/admin/onboarding/templates";
  };
  "routes/(admin)/analytics/route.tsx": {
    id: "routes/(admin)/analytics/route";
    page: "/admin/analytics";
  };
  "routes/(admin)/workflows/index.tsx": {
    id: "routes/(admin)/workflows/index";
    page: "/admin/workflows";
  };
  "routes/(admin)/workflows/builder/route.tsx": {
    id: "routes/(admin)/workflows/builder/route";
    page: "/admin/workflows/builder";
  };
  "routes/(admin)/workflows/templates/route.tsx": {
    id: "routes/(admin)/workflows/templates/route";
    page: "/admin/workflows/templates";
  };
  "routes/(admin)/security/index.tsx": {
    id: "routes/(admin)/security/index";
    page: "/admin/security";
  };
  "routes/(admin)/security/users/route.tsx": {
    id: "routes/(admin)/security/users/route";
    page: "/admin/security/users";
  };
  "routes/(admin)/security/roles/route.tsx": {
    id: "routes/(admin)/security/roles/route";
    page: "/admin/security/roles";
  };
  "routes/(admin)/security/permissions/route.tsx": {
    id: "routes/(admin)/security/permissions/route";
    page: "/admin/security/permissions";
  };
  "routes/(admin)/security/audit-log/route.tsx": {
    id: "routes/(admin)/security/audit-log/route";
    page: "/admin/security/audit-log";
  };
  "routes/(admin)/reports/index.tsx": {
    id: "routes/(admin)/reports/index";
    page: "/admin/reports";
  };
  "routes/(admin)/reports/[reportId]/route.tsx": {
    id: "routes/(admin)/reports/[reportId]/route";
    page: "/admin/reports/:reportId";
  };
  "routes/(admin)/lms/index.tsx": {
    id: "routes/(admin)/lms/index";
    page: "/admin/lms";
  };
  "routes/(admin)/lms/courses/route.tsx": {
    id: "routes/(admin)/lms/courses/route";
    page: "/admin/lms/courses";
  };
  "routes/(admin)/lms/assignments/route.tsx": {
    id: "routes/(admin)/lms/assignments/route";
    page: "/admin/lms/assignments";
  };
  "routes/(admin)/settings/index.tsx": {
    id: "routes/(admin)/settings/index";
    page: "/admin/settings";
  };
  "routes/(admin)/settings/tenant/route.tsx": {
    id: "routes/(admin)/settings/tenant/route";
    page: "/admin/settings/tenant";
  };
  "routes/(admin)/settings/integrations/route.tsx": {
    id: "routes/(admin)/settings/integrations/route";
    page: "/admin/settings/integrations";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/(auth)/layout": typeof import("./app/routes/(auth)/layout.tsx");
  "routes/(auth)/login/route": typeof import("./app/routes/(auth)/login/route.tsx");
  "routes/(auth)/mfa/route": typeof import("./app/routes/(auth)/mfa/route.tsx");
  "routes/(auth)/forgot-password/route": typeof import("./app/routes/(auth)/forgot-password/route.tsx");
  "routes/(auth)/reset-password/route": typeof import("./app/routes/(auth)/reset-password/route.tsx");
  "routes/(app)/layout": typeof import("./app/routes/(app)/layout.tsx");
  "routes/(app)/dashboard/route": typeof import("./app/routes/(app)/dashboard/route.tsx");
  "routes/(app)/me/index": typeof import("./app/routes/(app)/me/index.tsx");
  "routes/(app)/me/profile/route": typeof import("./app/routes/(app)/me/profile/route.tsx");
  "routes/(app)/me/time/route": typeof import("./app/routes/(app)/me/time/route.tsx");
  "routes/(app)/me/leave/route": typeof import("./app/routes/(app)/me/leave/route.tsx");
  "routes/(app)/me/benefits/route": typeof import("./app/routes/(app)/me/benefits/route.tsx");
  "routes/(app)/me/documents/route": typeof import("./app/routes/(app)/me/documents/route.tsx");
  "routes/(app)/me/learning/route": typeof import("./app/routes/(app)/me/learning/route.tsx");
  "routes/(app)/me/cases/route": typeof import("./app/routes/(app)/me/cases/route.tsx");
  "routes/(app)/me/competencies/route": typeof import("./app/routes/(app)/me/competencies/route.tsx");
  "routes/(app)/me/onboarding/route": typeof import("./app/routes/(app)/me/onboarding/route.tsx");
  "routes/(app)/manager/index": typeof import("./app/routes/(app)/manager/index.tsx");
  "routes/(app)/manager/team/route": typeof import("./app/routes/(app)/manager/team/route.tsx");
  "routes/(app)/manager/approvals/route": typeof import("./app/routes/(app)/manager/approvals/route.tsx");
  "routes/(app)/manager/schedules/route": typeof import("./app/routes/(app)/manager/schedules/route.tsx");
  "routes/(app)/manager/performance/route": typeof import("./app/routes/(app)/manager/performance/route.tsx");
  "routes/(admin)/layout": typeof import("./app/routes/(admin)/layout.tsx");
  "routes/(admin)/dashboard/route": typeof import("./app/routes/(admin)/dashboard/route.tsx");
  "routes/(admin)/hr/index": typeof import("./app/routes/(admin)/hr/index.tsx");
  "routes/(admin)/hr/employees/route": typeof import("./app/routes/(admin)/hr/employees/route.tsx");
  "routes/(admin)/hr/employees/[employeeId]/route": typeof import("./app/routes/(admin)/hr/employees/[employeeId]/route.tsx");
  "routes/(admin)/hr/positions/route": typeof import("./app/routes/(admin)/hr/positions/route.tsx");
  "routes/(admin)/hr/departments/route": typeof import("./app/routes/(admin)/hr/departments/route.tsx");
  "routes/(admin)/hr/organization/route": typeof import("./app/routes/(admin)/hr/organization/route.tsx");
  "routes/(admin)/hr/org-chart/route": typeof import("./app/routes/(admin)/hr/org-chart/route.tsx");
  "routes/(admin)/time/index": typeof import("./app/routes/(admin)/time/index.tsx");
  "routes/(admin)/time/timesheets/route": typeof import("./app/routes/(admin)/time/timesheets/route.tsx");
  "routes/(admin)/time/schedules/route": typeof import("./app/routes/(admin)/time/schedules/route.tsx");
  "routes/(admin)/absence/index": typeof import("./app/routes/(admin)/absence/index.tsx");
  "routes/(admin)/talent/index": typeof import("./app/routes/(admin)/talent/index.tsx");
  "routes/(admin)/talent/performance/route": typeof import("./app/routes/(admin)/talent/performance/route.tsx");
  "routes/(admin)/talent/competencies/route": typeof import("./app/routes/(admin)/talent/competencies/route.tsx");
  "routes/(admin)/talent/succession/route": typeof import("./app/routes/(admin)/talent/succession/route.tsx");
  "routes/(admin)/talent/recruitment/route": typeof import("./app/routes/(admin)/talent/recruitment/route.tsx");
  "routes/(admin)/talent/recruitment/candidates/route": typeof import("./app/routes/(admin)/talent/recruitment/candidates/route.tsx");
  "routes/(admin)/benefits/route": typeof import("./app/routes/(admin)/benefits/route.tsx");
  "routes/(admin)/cases/index": typeof import("./app/routes/(admin)/cases/index.tsx");
  "routes/(admin)/cases/[caseId]/route": typeof import("./app/routes/(admin)/cases/[caseId]/route.tsx");
  "routes/(admin)/onboarding/index": typeof import("./app/routes/(admin)/onboarding/index.tsx");
  "routes/(admin)/onboarding/templates/route": typeof import("./app/routes/(admin)/onboarding/templates/route.tsx");
  "routes/(admin)/analytics/route": typeof import("./app/routes/(admin)/analytics/route.tsx");
  "routes/(admin)/workflows/index": typeof import("./app/routes/(admin)/workflows/index.tsx");
  "routes/(admin)/workflows/builder/route": typeof import("./app/routes/(admin)/workflows/builder/route.tsx");
  "routes/(admin)/workflows/templates/route": typeof import("./app/routes/(admin)/workflows/templates/route.tsx");
  "routes/(admin)/security/index": typeof import("./app/routes/(admin)/security/index.tsx");
  "routes/(admin)/security/users/route": typeof import("./app/routes/(admin)/security/users/route.tsx");
  "routes/(admin)/security/roles/route": typeof import("./app/routes/(admin)/security/roles/route.tsx");
  "routes/(admin)/security/permissions/route": typeof import("./app/routes/(admin)/security/permissions/route.tsx");
  "routes/(admin)/security/audit-log/route": typeof import("./app/routes/(admin)/security/audit-log/route.tsx");
  "routes/(admin)/reports/index": typeof import("./app/routes/(admin)/reports/index.tsx");
  "routes/(admin)/reports/[reportId]/route": typeof import("./app/routes/(admin)/reports/[reportId]/route.tsx");
  "routes/(admin)/lms/index": typeof import("./app/routes/(admin)/lms/index.tsx");
  "routes/(admin)/lms/courses/route": typeof import("./app/routes/(admin)/lms/courses/route.tsx");
  "routes/(admin)/lms/assignments/route": typeof import("./app/routes/(admin)/lms/assignments/route.tsx");
  "routes/(admin)/settings/index": typeof import("./app/routes/(admin)/settings/index.tsx");
  "routes/(admin)/settings/tenant/route": typeof import("./app/routes/(admin)/settings/tenant/route.tsx");
  "routes/(admin)/settings/integrations/route": typeof import("./app/routes/(admin)/settings/integrations/route.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};